<?php
/**
 * NodesTasksApi
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pdm\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use ClientApi\Pdm\ApiException;
use ClientApi\Pdm\Configuration;
use ClientApi\Pdm\FormDataProcessor;
use ClientApi\Pdm\HeaderSelector;
use ClientApi\Pdm\ObjectSerializer;

/**
 * NodesTasksApi Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NodesTasksApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'nodesTasksDeleteTasks' => [
            'application/json',
        ],
        'nodesTasksGetLog' => [
            'application/json',
        ],
        'nodesTasksGetNodesByNodeTasksByUpid' => [
            'application/json',
        ],
        'nodesTasksGetStatus' => [
            'application/json',
        ],
        'nodesTasksGetTasks' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation nodesTasksDeleteTasks
     *
     * Try to stop a task
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  string $upid Unique Process/Task Identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksDeleteTasks'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pdm\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pdm\Model\NodesTasksDeleteTasksResponse|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError
     */
    public function nodesTasksDeleteTasks($node, $upid, string $contentType = self::contentTypes['nodesTasksDeleteTasks'][0])
    {
        list($response) = $this->nodesTasksDeleteTasksWithHttpInfo($node, $upid, $contentType);
        return $response;
    }

    /**
     * Operation nodesTasksDeleteTasksWithHttpInfo
     *
     * Try to stop a task
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  string $upid Unique Process/Task Identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksDeleteTasks'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pdm\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pdm\Model\NodesTasksDeleteTasksResponse|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError, HTTP status code, HTTP response headers (array of strings)
     */
    public function nodesTasksDeleteTasksWithHttpInfo($node, $upid, string $contentType = self::contentTypes['nodesTasksDeleteTasks'][0])
    {
        $request = $this->nodesTasksDeleteTasksRequest($node, $upid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\NodesTasksDeleteTasksResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pdm\Model\NodesTasksDeleteTasksResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\NodesTasksDeleteTasksResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation nodesTasksDeleteTasksAsync
     *
     * Try to stop a task
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  string $upid Unique Process/Task Identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksDeleteTasks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function nodesTasksDeleteTasksAsync($node, $upid, string $contentType = self::contentTypes['nodesTasksDeleteTasks'][0])
    {
        return $this->nodesTasksDeleteTasksAsyncWithHttpInfo($node, $upid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation nodesTasksDeleteTasksAsyncWithHttpInfo
     *
     * Try to stop a task
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  string $upid Unique Process/Task Identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksDeleteTasks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function nodesTasksDeleteTasksAsyncWithHttpInfo($node, $upid, string $contentType = self::contentTypes['nodesTasksDeleteTasks'][0])
    {
        $returnType = '\ClientApi\Pdm\Model\NodesTasksDeleteTasksResponse';
        $request = $this->nodesTasksDeleteTasksRequest($node, $upid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'nodesTasksDeleteTasks'
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  string $upid Unique Process/Task Identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksDeleteTasks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function nodesTasksDeleteTasksRequest($node, $upid, string $contentType = self::contentTypes['nodesTasksDeleteTasks'][0])
    {

        // verify the required parameter 'node' is set
        if ($node === null || (is_array($node) && count($node) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $node when calling nodesTasksDeleteTasks'
            );
        }
        if (!preg_match("/^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/", $node)) {
            throw new \InvalidArgumentException("invalid value for \"node\" when calling NodesTasksApi.nodesTasksDeleteTasks, must conform to the pattern /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/.");
        }
        
        // verify the required parameter 'upid' is set
        if ($upid === null || (is_array($upid) && count($upid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upid when calling nodesTasksDeleteTasks'
            );
        }
        if (strlen($upid) < 36) {
            throw new \InvalidArgumentException('invalid length for "$upid" when calling NodesTasksApi.nodesTasksDeleteTasks, must be bigger than or equal to 36.');
        }
        

        $resourcePath = '/nodes/{node}/tasks/{upid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($node !== null) {
            $resourcePath = str_replace(
                '{node}',
                ObjectSerializer::toPathValue($node),
                $resourcePath
            );
        }
        // path params
        if ($upid !== null) {
            $resourcePath = str_replace(
                '{upid}',
                ObjectSerializer::toPathValue($upid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation nodesTasksGetLog
     *
     * Read the task log
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  string $upid Unique Process/Task Identifier (required)
     * @param  bool|null $download Whether the tasklog file should be downloaded. This parameter can&#39;t be used in conjunction with other parameters (optional, default to false)
     * @param  int|null $limit The amount of lines to read from the tasklog. Setting this parameter to 0 will return all lines until the end of the file. (optional, default to 50)
     * @param  int|null $start Start at this line when reading the tasklog (optional, default to 0)
     * @param  bool|null $test_status Test task status, and set result attribute \&quot;active\&quot; accordingly. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetLog'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pdm\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pdm\Model\NodesTasksGetLogResponse|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError
     */
    public function nodesTasksGetLog($node, $upid, $download = false, $limit = 50, $start = 0, $test_status = null, string $contentType = self::contentTypes['nodesTasksGetLog'][0])
    {
        list($response) = $this->nodesTasksGetLogWithHttpInfo($node, $upid, $download, $limit, $start, $test_status, $contentType);
        return $response;
    }

    /**
     * Operation nodesTasksGetLogWithHttpInfo
     *
     * Read the task log
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  string $upid Unique Process/Task Identifier (required)
     * @param  bool|null $download Whether the tasklog file should be downloaded. This parameter can&#39;t be used in conjunction with other parameters (optional, default to false)
     * @param  int|null $limit The amount of lines to read from the tasklog. Setting this parameter to 0 will return all lines until the end of the file. (optional, default to 50)
     * @param  int|null $start Start at this line when reading the tasklog (optional, default to 0)
     * @param  bool|null $test_status Test task status, and set result attribute \&quot;active\&quot; accordingly. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetLog'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pdm\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pdm\Model\NodesTasksGetLogResponse|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError, HTTP status code, HTTP response headers (array of strings)
     */
    public function nodesTasksGetLogWithHttpInfo($node, $upid, $download = false, $limit = 50, $start = 0, $test_status = null, string $contentType = self::contentTypes['nodesTasksGetLog'][0])
    {
        $request = $this->nodesTasksGetLogRequest($node, $upid, $download, $limit, $start, $test_status, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\NodesTasksGetLogResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pdm\Model\NodesTasksGetLogResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\NodesTasksGetLogResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation nodesTasksGetLogAsync
     *
     * Read the task log
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  string $upid Unique Process/Task Identifier (required)
     * @param  bool|null $download Whether the tasklog file should be downloaded. This parameter can&#39;t be used in conjunction with other parameters (optional, default to false)
     * @param  int|null $limit The amount of lines to read from the tasklog. Setting this parameter to 0 will return all lines until the end of the file. (optional, default to 50)
     * @param  int|null $start Start at this line when reading the tasklog (optional, default to 0)
     * @param  bool|null $test_status Test task status, and set result attribute \&quot;active\&quot; accordingly. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetLog'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function nodesTasksGetLogAsync($node, $upid, $download = false, $limit = 50, $start = 0, $test_status = null, string $contentType = self::contentTypes['nodesTasksGetLog'][0])
    {
        return $this->nodesTasksGetLogAsyncWithHttpInfo($node, $upid, $download, $limit, $start, $test_status, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation nodesTasksGetLogAsyncWithHttpInfo
     *
     * Read the task log
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  string $upid Unique Process/Task Identifier (required)
     * @param  bool|null $download Whether the tasklog file should be downloaded. This parameter can&#39;t be used in conjunction with other parameters (optional, default to false)
     * @param  int|null $limit The amount of lines to read from the tasklog. Setting this parameter to 0 will return all lines until the end of the file. (optional, default to 50)
     * @param  int|null $start Start at this line when reading the tasklog (optional, default to 0)
     * @param  bool|null $test_status Test task status, and set result attribute \&quot;active\&quot; accordingly. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetLog'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function nodesTasksGetLogAsyncWithHttpInfo($node, $upid, $download = false, $limit = 50, $start = 0, $test_status = null, string $contentType = self::contentTypes['nodesTasksGetLog'][0])
    {
        $returnType = '\ClientApi\Pdm\Model\NodesTasksGetLogResponse';
        $request = $this->nodesTasksGetLogRequest($node, $upid, $download, $limit, $start, $test_status, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'nodesTasksGetLog'
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  string $upid Unique Process/Task Identifier (required)
     * @param  bool|null $download Whether the tasklog file should be downloaded. This parameter can&#39;t be used in conjunction with other parameters (optional, default to false)
     * @param  int|null $limit The amount of lines to read from the tasklog. Setting this parameter to 0 will return all lines until the end of the file. (optional, default to 50)
     * @param  int|null $start Start at this line when reading the tasklog (optional, default to 0)
     * @param  bool|null $test_status Test task status, and set result attribute \&quot;active\&quot; accordingly. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetLog'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function nodesTasksGetLogRequest($node, $upid, $download = false, $limit = 50, $start = 0, $test_status = null, string $contentType = self::contentTypes['nodesTasksGetLog'][0])
    {

        // verify the required parameter 'node' is set
        if ($node === null || (is_array($node) && count($node) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $node when calling nodesTasksGetLog'
            );
        }
        if (!preg_match("/^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/", $node)) {
            throw new \InvalidArgumentException("invalid value for \"node\" when calling NodesTasksApi.nodesTasksGetLog, must conform to the pattern /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/.");
        }
        
        // verify the required parameter 'upid' is set
        if ($upid === null || (is_array($upid) && count($upid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upid when calling nodesTasksGetLog'
            );
        }
        if (strlen($upid) < 36) {
            throw new \InvalidArgumentException('invalid length for "$upid" when calling NodesTasksApi.nodesTasksGetLog, must be bigger than or equal to 36.');
        }
        

        if ($limit !== null && $limit < 0) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling NodesTasksApi.nodesTasksGetLog, must be bigger than or equal to 0.');
        }
        
        if ($start !== null && $start < 0) {
            throw new \InvalidArgumentException('invalid value for "$start" when calling NodesTasksApi.nodesTasksGetLog, must be bigger than or equal to 0.');
        }
        


        $resourcePath = '/nodes/{node}/tasks/{upid}/log';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $download,
            'download', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start,
            'start', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $test_status,
            'test-status', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($node !== null) {
            $resourcePath = str_replace(
                '{node}',
                ObjectSerializer::toPathValue($node),
                $resourcePath
            );
        }
        // path params
        if ($upid !== null) {
            $resourcePath = str_replace(
                '{upid}',
                ObjectSerializer::toPathValue($upid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation nodesTasksGetNodesByNodeTasksByUpid
     *
     * Directory index
     *
     * @param  string $node node (required)
     * @param  string $upid upid (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetNodesByNodeTasksByUpid'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pdm\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pdm\Model\NodesTasksGetNodesByNodeTasksByUpidResponse|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError
     */
    public function nodesTasksGetNodesByNodeTasksByUpid($node, $upid, string $contentType = self::contentTypes['nodesTasksGetNodesByNodeTasksByUpid'][0])
    {
        list($response) = $this->nodesTasksGetNodesByNodeTasksByUpidWithHttpInfo($node, $upid, $contentType);
        return $response;
    }

    /**
     * Operation nodesTasksGetNodesByNodeTasksByUpidWithHttpInfo
     *
     * Directory index
     *
     * @param  string $node (required)
     * @param  string $upid (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetNodesByNodeTasksByUpid'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pdm\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pdm\Model\NodesTasksGetNodesByNodeTasksByUpidResponse|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError, HTTP status code, HTTP response headers (array of strings)
     */
    public function nodesTasksGetNodesByNodeTasksByUpidWithHttpInfo($node, $upid, string $contentType = self::contentTypes['nodesTasksGetNodesByNodeTasksByUpid'][0])
    {
        $request = $this->nodesTasksGetNodesByNodeTasksByUpidRequest($node, $upid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\NodesTasksGetNodesByNodeTasksByUpidResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pdm\Model\NodesTasksGetNodesByNodeTasksByUpidResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\NodesTasksGetNodesByNodeTasksByUpidResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation nodesTasksGetNodesByNodeTasksByUpidAsync
     *
     * Directory index
     *
     * @param  string $node (required)
     * @param  string $upid (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetNodesByNodeTasksByUpid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function nodesTasksGetNodesByNodeTasksByUpidAsync($node, $upid, string $contentType = self::contentTypes['nodesTasksGetNodesByNodeTasksByUpid'][0])
    {
        return $this->nodesTasksGetNodesByNodeTasksByUpidAsyncWithHttpInfo($node, $upid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation nodesTasksGetNodesByNodeTasksByUpidAsyncWithHttpInfo
     *
     * Directory index
     *
     * @param  string $node (required)
     * @param  string $upid (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetNodesByNodeTasksByUpid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function nodesTasksGetNodesByNodeTasksByUpidAsyncWithHttpInfo($node, $upid, string $contentType = self::contentTypes['nodesTasksGetNodesByNodeTasksByUpid'][0])
    {
        $returnType = '\ClientApi\Pdm\Model\NodesTasksGetNodesByNodeTasksByUpidResponse';
        $request = $this->nodesTasksGetNodesByNodeTasksByUpidRequest($node, $upid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'nodesTasksGetNodesByNodeTasksByUpid'
     *
     * @param  string $node (required)
     * @param  string $upid (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetNodesByNodeTasksByUpid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function nodesTasksGetNodesByNodeTasksByUpidRequest($node, $upid, string $contentType = self::contentTypes['nodesTasksGetNodesByNodeTasksByUpid'][0])
    {

        // verify the required parameter 'node' is set
        if ($node === null || (is_array($node) && count($node) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $node when calling nodesTasksGetNodesByNodeTasksByUpid'
            );
        }

        // verify the required parameter 'upid' is set
        if ($upid === null || (is_array($upid) && count($upid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upid when calling nodesTasksGetNodesByNodeTasksByUpid'
            );
        }


        $resourcePath = '/nodes/{node}/tasks/{upid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($node !== null) {
            $resourcePath = str_replace(
                '{node}',
                ObjectSerializer::toPathValue($node),
                $resourcePath
            );
        }
        // path params
        if ($upid !== null) {
            $resourcePath = str_replace(
                '{upid}',
                ObjectSerializer::toPathValue($upid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation nodesTasksGetStatus
     *
     * Get task status
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  string $upid Unique Process/Task Identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetStatus'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pdm\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pdm\Model\NodesTasksGetStatusResponse|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError
     */
    public function nodesTasksGetStatus($node, $upid, string $contentType = self::contentTypes['nodesTasksGetStatus'][0])
    {
        list($response) = $this->nodesTasksGetStatusWithHttpInfo($node, $upid, $contentType);
        return $response;
    }

    /**
     * Operation nodesTasksGetStatusWithHttpInfo
     *
     * Get task status
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  string $upid Unique Process/Task Identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetStatus'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pdm\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pdm\Model\NodesTasksGetStatusResponse|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError, HTTP status code, HTTP response headers (array of strings)
     */
    public function nodesTasksGetStatusWithHttpInfo($node, $upid, string $contentType = self::contentTypes['nodesTasksGetStatus'][0])
    {
        $request = $this->nodesTasksGetStatusRequest($node, $upid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\NodesTasksGetStatusResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pdm\Model\NodesTasksGetStatusResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\NodesTasksGetStatusResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation nodesTasksGetStatusAsync
     *
     * Get task status
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  string $upid Unique Process/Task Identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function nodesTasksGetStatusAsync($node, $upid, string $contentType = self::contentTypes['nodesTasksGetStatus'][0])
    {
        return $this->nodesTasksGetStatusAsyncWithHttpInfo($node, $upid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation nodesTasksGetStatusAsyncWithHttpInfo
     *
     * Get task status
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  string $upid Unique Process/Task Identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function nodesTasksGetStatusAsyncWithHttpInfo($node, $upid, string $contentType = self::contentTypes['nodesTasksGetStatus'][0])
    {
        $returnType = '\ClientApi\Pdm\Model\NodesTasksGetStatusResponse';
        $request = $this->nodesTasksGetStatusRequest($node, $upid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'nodesTasksGetStatus'
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  string $upid Unique Process/Task Identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function nodesTasksGetStatusRequest($node, $upid, string $contentType = self::contentTypes['nodesTasksGetStatus'][0])
    {

        // verify the required parameter 'node' is set
        if ($node === null || (is_array($node) && count($node) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $node when calling nodesTasksGetStatus'
            );
        }
        if (!preg_match("/^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/", $node)) {
            throw new \InvalidArgumentException("invalid value for \"node\" when calling NodesTasksApi.nodesTasksGetStatus, must conform to the pattern /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/.");
        }
        
        // verify the required parameter 'upid' is set
        if ($upid === null || (is_array($upid) && count($upid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upid when calling nodesTasksGetStatus'
            );
        }
        if (strlen($upid) < 36) {
            throw new \InvalidArgumentException('invalid length for "$upid" when calling NodesTasksApi.nodesTasksGetStatus, must be bigger than or equal to 36.');
        }
        

        $resourcePath = '/nodes/{node}/tasks/{upid}/status';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($node !== null) {
            $resourcePath = str_replace(
                '{node}',
                ObjectSerializer::toPathValue($node),
                $resourcePath
            );
        }
        // path params
        if ($upid !== null) {
            $resourcePath = str_replace(
                '{upid}',
                ObjectSerializer::toPathValue($upid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation nodesTasksGetTasks
     *
     * List tasks
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  bool|null $errors Only list erroneous tasks. (optional, default to false)
     * @param  int|null $limit Only list this amount of tasks. (0 means no limit) (optional, default to 50)
     * @param  bool|null $running Only list running tasks. (optional, default to false)
     * @param  int|null $since Only list tasks since this UNIX epoch. (optional)
     * @param  int|null $start List tasks beginning from this offset. (optional, default to 0)
     * @param  \ClientApi\Pdm\Model\PdmStatusfilterEnum[]|null $statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param  string|null $typefilter Only list tasks whose type contains this. (optional)
     * @param  int|null $until Only list tasks until this UNIX epoch. (optional)
     * @param  string|null $userfilter Only list tasks from this user. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetTasks'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pdm\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pdm\Model\NodesTasksGetTasksResponse|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError
     */
    public function nodesTasksGetTasks($node, $errors = false, $limit = 50, $running = false, $since = null, $start = 0, $statusfilter = null, $typefilter = null, $until = null, $userfilter = null, string $contentType = self::contentTypes['nodesTasksGetTasks'][0])
    {
        list($response) = $this->nodesTasksGetTasksWithHttpInfo($node, $errors, $limit, $running, $since, $start, $statusfilter, $typefilter, $until, $userfilter, $contentType);
        return $response;
    }

    /**
     * Operation nodesTasksGetTasksWithHttpInfo
     *
     * List tasks
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  bool|null $errors Only list erroneous tasks. (optional, default to false)
     * @param  int|null $limit Only list this amount of tasks. (0 means no limit) (optional, default to 50)
     * @param  bool|null $running Only list running tasks. (optional, default to false)
     * @param  int|null $since Only list tasks since this UNIX epoch. (optional)
     * @param  int|null $start List tasks beginning from this offset. (optional, default to 0)
     * @param  \ClientApi\Pdm\Model\PdmStatusfilterEnum[]|null $statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param  string|null $typefilter Only list tasks whose type contains this. (optional)
     * @param  int|null $until Only list tasks until this UNIX epoch. (optional)
     * @param  string|null $userfilter Only list tasks from this user. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetTasks'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pdm\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pdm\Model\NodesTasksGetTasksResponse|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError, HTTP status code, HTTP response headers (array of strings)
     */
    public function nodesTasksGetTasksWithHttpInfo($node, $errors = false, $limit = 50, $running = false, $since = null, $start = 0, $statusfilter = null, $typefilter = null, $until = null, $userfilter = null, string $contentType = self::contentTypes['nodesTasksGetTasks'][0])
    {
        $request = $this->nodesTasksGetTasksRequest($node, $errors, $limit, $running, $since, $start, $statusfilter, $typefilter, $until, $userfilter, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\NodesTasksGetTasksResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pdm\Model\NodesTasksGetTasksResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\NodesTasksGetTasksResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation nodesTasksGetTasksAsync
     *
     * List tasks
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  bool|null $errors Only list erroneous tasks. (optional, default to false)
     * @param  int|null $limit Only list this amount of tasks. (0 means no limit) (optional, default to 50)
     * @param  bool|null $running Only list running tasks. (optional, default to false)
     * @param  int|null $since Only list tasks since this UNIX epoch. (optional)
     * @param  int|null $start List tasks beginning from this offset. (optional, default to 0)
     * @param  \ClientApi\Pdm\Model\PdmStatusfilterEnum[]|null $statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param  string|null $typefilter Only list tasks whose type contains this. (optional)
     * @param  int|null $until Only list tasks until this UNIX epoch. (optional)
     * @param  string|null $userfilter Only list tasks from this user. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetTasks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function nodesTasksGetTasksAsync($node, $errors = false, $limit = 50, $running = false, $since = null, $start = 0, $statusfilter = null, $typefilter = null, $until = null, $userfilter = null, string $contentType = self::contentTypes['nodesTasksGetTasks'][0])
    {
        return $this->nodesTasksGetTasksAsyncWithHttpInfo($node, $errors, $limit, $running, $since, $start, $statusfilter, $typefilter, $until, $userfilter, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation nodesTasksGetTasksAsyncWithHttpInfo
     *
     * List tasks
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  bool|null $errors Only list erroneous tasks. (optional, default to false)
     * @param  int|null $limit Only list this amount of tasks. (0 means no limit) (optional, default to 50)
     * @param  bool|null $running Only list running tasks. (optional, default to false)
     * @param  int|null $since Only list tasks since this UNIX epoch. (optional)
     * @param  int|null $start List tasks beginning from this offset. (optional, default to 0)
     * @param  \ClientApi\Pdm\Model\PdmStatusfilterEnum[]|null $statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param  string|null $typefilter Only list tasks whose type contains this. (optional)
     * @param  int|null $until Only list tasks until this UNIX epoch. (optional)
     * @param  string|null $userfilter Only list tasks from this user. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetTasks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function nodesTasksGetTasksAsyncWithHttpInfo($node, $errors = false, $limit = 50, $running = false, $since = null, $start = 0, $statusfilter = null, $typefilter = null, $until = null, $userfilter = null, string $contentType = self::contentTypes['nodesTasksGetTasks'][0])
    {
        $returnType = '\ClientApi\Pdm\Model\NodesTasksGetTasksResponse';
        $request = $this->nodesTasksGetTasksRequest($node, $errors, $limit, $running, $since, $start, $statusfilter, $typefilter, $until, $userfilter, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'nodesTasksGetTasks'
     *
     * @param  string $node Node name (or &#39;localhost&#39;) (required)
     * @param  bool|null $errors Only list erroneous tasks. (optional, default to false)
     * @param  int|null $limit Only list this amount of tasks. (0 means no limit) (optional, default to 50)
     * @param  bool|null $running Only list running tasks. (optional, default to false)
     * @param  int|null $since Only list tasks since this UNIX epoch. (optional)
     * @param  int|null $start List tasks beginning from this offset. (optional, default to 0)
     * @param  \ClientApi\Pdm\Model\PdmStatusfilterEnum[]|null $statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param  string|null $typefilter Only list tasks whose type contains this. (optional)
     * @param  int|null $until Only list tasks until this UNIX epoch. (optional)
     * @param  string|null $userfilter Only list tasks from this user. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nodesTasksGetTasks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function nodesTasksGetTasksRequest($node, $errors = false, $limit = 50, $running = false, $since = null, $start = 0, $statusfilter = null, $typefilter = null, $until = null, $userfilter = null, string $contentType = self::contentTypes['nodesTasksGetTasks'][0])
    {

        // verify the required parameter 'node' is set
        if ($node === null || (is_array($node) && count($node) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $node when calling nodesTasksGetTasks'
            );
        }
        if (!preg_match("/^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/", $node)) {
            throw new \InvalidArgumentException("invalid value for \"node\" when calling NodesTasksApi.nodesTasksGetTasks, must conform to the pattern /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/.");
        }
        










        $resourcePath = '/nodes/{node}/tasks';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $errors,
            'errors', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $running,
            'running', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $since,
            'since', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start,
            'start', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $statusfilter,
            'statusfilter', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $typefilter,
            'typefilter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $until,
            'until', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $userfilter,
            'userfilter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($node !== null) {
            $resourcePath = str_replace(
                '{node}',
                ObjectSerializer::toPathValue($node),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
