<?php
/**
 * RemotesTasksApi
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pdm\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use ClientApi\Pdm\ApiException;
use ClientApi\Pdm\Configuration;
use ClientApi\Pdm\FormDataProcessor;
use ClientApi\Pdm\HeaderSelector;
use ClientApi\Pdm\ObjectSerializer;

/**
 * RemotesTasksApi Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RemotesTasksApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'remotesTasksGetList' => [
            'application/json',
        ],
        'remotesTasksGetStatistics' => [
            'application/json',
        ],
        'remotesTasksGetTasks' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation remotesTasksGetList
     *
     * Get the list of tasks for all remotes
     *
     * @param  bool|null $errors Only list erroneous tasks. (optional, default to 0)
     * @param  int|null $limit Only list this amount of tasks. (0 means no limit) (optional, default to 50)
     * @param  string|null $remote Remote ID. (optional)
     * @param  bool|null $running Only list running tasks. (optional, default to 0)
     * @param  int|null $since Only list tasks since this UNIX epoch. (optional)
     * @param  int|null $start List tasks beginning from this offset. (optional, default to 0)
     * @param  \ClientApi\Pdm\Model\PdmStatusfilterEnum[]|null $statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param  string|null $typefilter Only list tasks whose type contains this. (optional)
     * @param  int|null $until Only list tasks until this UNIX epoch. (optional)
     * @param  string|null $userfilter Only list tasks from this user. (optional)
     * @param  string|null $view View name. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['remotesTasksGetList'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pdm\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pdm\Model\RemotesTasksGetListResponse|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError
     */
    public function remotesTasksGetList($errors = 0, $limit = 50, $remote = null, $running = 0, $since = null, $start = 0, $statusfilter = null, $typefilter = null, $until = null, $userfilter = null, $view = null, string $contentType = self::contentTypes['remotesTasksGetList'][0])
    {
        list($response) = $this->remotesTasksGetListWithHttpInfo($errors, $limit, $remote, $running, $since, $start, $statusfilter, $typefilter, $until, $userfilter, $view, $contentType);
        return $response;
    }

    /**
     * Operation remotesTasksGetListWithHttpInfo
     *
     * Get the list of tasks for all remotes
     *
     * @param  bool|null $errors Only list erroneous tasks. (optional, default to 0)
     * @param  int|null $limit Only list this amount of tasks. (0 means no limit) (optional, default to 50)
     * @param  string|null $remote Remote ID. (optional)
     * @param  bool|null $running Only list running tasks. (optional, default to 0)
     * @param  int|null $since Only list tasks since this UNIX epoch. (optional)
     * @param  int|null $start List tasks beginning from this offset. (optional, default to 0)
     * @param  \ClientApi\Pdm\Model\PdmStatusfilterEnum[]|null $statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param  string|null $typefilter Only list tasks whose type contains this. (optional)
     * @param  int|null $until Only list tasks until this UNIX epoch. (optional)
     * @param  string|null $userfilter Only list tasks from this user. (optional)
     * @param  string|null $view View name. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['remotesTasksGetList'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pdm\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pdm\Model\RemotesTasksGetListResponse|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError, HTTP status code, HTTP response headers (array of strings)
     */
    public function remotesTasksGetListWithHttpInfo($errors = 0, $limit = 50, $remote = null, $running = 0, $since = null, $start = 0, $statusfilter = null, $typefilter = null, $until = null, $userfilter = null, $view = null, string $contentType = self::contentTypes['remotesTasksGetList'][0])
    {
        $request = $this->remotesTasksGetListRequest($errors, $limit, $remote, $running, $since, $start, $statusfilter, $typefilter, $until, $userfilter, $view, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\RemotesTasksGetListResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pdm\Model\RemotesTasksGetListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\RemotesTasksGetListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation remotesTasksGetListAsync
     *
     * Get the list of tasks for all remotes
     *
     * @param  bool|null $errors Only list erroneous tasks. (optional, default to 0)
     * @param  int|null $limit Only list this amount of tasks. (0 means no limit) (optional, default to 50)
     * @param  string|null $remote Remote ID. (optional)
     * @param  bool|null $running Only list running tasks. (optional, default to 0)
     * @param  int|null $since Only list tasks since this UNIX epoch. (optional)
     * @param  int|null $start List tasks beginning from this offset. (optional, default to 0)
     * @param  \ClientApi\Pdm\Model\PdmStatusfilterEnum[]|null $statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param  string|null $typefilter Only list tasks whose type contains this. (optional)
     * @param  int|null $until Only list tasks until this UNIX epoch. (optional)
     * @param  string|null $userfilter Only list tasks from this user. (optional)
     * @param  string|null $view View name. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['remotesTasksGetList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function remotesTasksGetListAsync($errors = 0, $limit = 50, $remote = null, $running = 0, $since = null, $start = 0, $statusfilter = null, $typefilter = null, $until = null, $userfilter = null, $view = null, string $contentType = self::contentTypes['remotesTasksGetList'][0])
    {
        return $this->remotesTasksGetListAsyncWithHttpInfo($errors, $limit, $remote, $running, $since, $start, $statusfilter, $typefilter, $until, $userfilter, $view, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation remotesTasksGetListAsyncWithHttpInfo
     *
     * Get the list of tasks for all remotes
     *
     * @param  bool|null $errors Only list erroneous tasks. (optional, default to 0)
     * @param  int|null $limit Only list this amount of tasks. (0 means no limit) (optional, default to 50)
     * @param  string|null $remote Remote ID. (optional)
     * @param  bool|null $running Only list running tasks. (optional, default to 0)
     * @param  int|null $since Only list tasks since this UNIX epoch. (optional)
     * @param  int|null $start List tasks beginning from this offset. (optional, default to 0)
     * @param  \ClientApi\Pdm\Model\PdmStatusfilterEnum[]|null $statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param  string|null $typefilter Only list tasks whose type contains this. (optional)
     * @param  int|null $until Only list tasks until this UNIX epoch. (optional)
     * @param  string|null $userfilter Only list tasks from this user. (optional)
     * @param  string|null $view View name. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['remotesTasksGetList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function remotesTasksGetListAsyncWithHttpInfo($errors = 0, $limit = 50, $remote = null, $running = 0, $since = null, $start = 0, $statusfilter = null, $typefilter = null, $until = null, $userfilter = null, $view = null, string $contentType = self::contentTypes['remotesTasksGetList'][0])
    {
        $returnType = '\ClientApi\Pdm\Model\RemotesTasksGetListResponse';
        $request = $this->remotesTasksGetListRequest($errors, $limit, $remote, $running, $since, $start, $statusfilter, $typefilter, $until, $userfilter, $view, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'remotesTasksGetList'
     *
     * @param  bool|null $errors Only list erroneous tasks. (optional, default to 0)
     * @param  int|null $limit Only list this amount of tasks. (0 means no limit) (optional, default to 50)
     * @param  string|null $remote Remote ID. (optional)
     * @param  bool|null $running Only list running tasks. (optional, default to 0)
     * @param  int|null $since Only list tasks since this UNIX epoch. (optional)
     * @param  int|null $start List tasks beginning from this offset. (optional, default to 0)
     * @param  \ClientApi\Pdm\Model\PdmStatusfilterEnum[]|null $statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param  string|null $typefilter Only list tasks whose type contains this. (optional)
     * @param  int|null $until Only list tasks until this UNIX epoch. (optional)
     * @param  string|null $userfilter Only list tasks from this user. (optional)
     * @param  string|null $view View name. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['remotesTasksGetList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function remotesTasksGetListRequest($errors = 0, $limit = 50, $remote = null, $running = 0, $since = null, $start = 0, $statusfilter = null, $typefilter = null, $until = null, $userfilter = null, $view = null, string $contentType = self::contentTypes['remotesTasksGetList'][0])
    {



        if ($remote !== null && strlen($remote) > 32) {
            throw new \InvalidArgumentException('invalid length for "$remote" when calling RemotesTasksApi.remotesTasksGetList, must be smaller than or equal to 32.');
        }
        if ($remote !== null && strlen($remote) < 2) {
            throw new \InvalidArgumentException('invalid length for "$remote" when calling RemotesTasksApi.remotesTasksGetList, must be bigger than or equal to 2.');
        }
        if ($remote !== null && !preg_match("/^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/", $remote)) {
            throw new \InvalidArgumentException("invalid value for \"remote\" when calling RemotesTasksApi.remotesTasksGetList, must conform to the pattern /^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/.");
        }
        







        if ($view !== null && strlen($view) > 32) {
            throw new \InvalidArgumentException('invalid length for "$view" when calling RemotesTasksApi.remotesTasksGetList, must be smaller than or equal to 32.');
        }
        if ($view !== null && strlen($view) < 2) {
            throw new \InvalidArgumentException('invalid length for "$view" when calling RemotesTasksApi.remotesTasksGetList, must be bigger than or equal to 2.');
        }
        if ($view !== null && !preg_match("/^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/", $view)) {
            throw new \InvalidArgumentException("invalid value for \"view\" when calling RemotesTasksApi.remotesTasksGetList, must conform to the pattern /^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/.");
        }
        

        $resourcePath = '/remotes/tasks/list';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $errors,
            'errors', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $remote,
            'remote', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $running,
            'running', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $since,
            'since', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start,
            'start', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $statusfilter,
            'statusfilter', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $typefilter,
            'typefilter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $until,
            'until', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $userfilter,
            'userfilter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $view,
            'view', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation remotesTasksGetStatistics
     *
     * Get task statistics for the specified filters
     *
     * @param  bool|null $errors Only list erroneous tasks. (optional, default to 0)
     * @param  int|null $limit Only list this amount of tasks. (0 means no limit) (optional, default to 50)
     * @param  string|null $remote Remote ID. (optional)
     * @param  bool|null $running Only list running tasks. (optional, default to 0)
     * @param  int|null $since Only list tasks since this UNIX epoch. (optional)
     * @param  int|null $start List tasks beginning from this offset. (optional, default to 0)
     * @param  \ClientApi\Pdm\Model\PdmStatusfilterEnum[]|null $statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param  string|null $typefilter Only list tasks whose type contains this. (optional)
     * @param  int|null $until Only list tasks until this UNIX epoch. (optional)
     * @param  string|null $userfilter Only list tasks from this user. (optional)
     * @param  string|null $view View name. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['remotesTasksGetStatistics'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pdm\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pdm\Model\RemotesTasksGetStatisticsResponse|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError
     */
    public function remotesTasksGetStatistics($errors = 0, $limit = 50, $remote = null, $running = 0, $since = null, $start = 0, $statusfilter = null, $typefilter = null, $until = null, $userfilter = null, $view = null, string $contentType = self::contentTypes['remotesTasksGetStatistics'][0])
    {
        list($response) = $this->remotesTasksGetStatisticsWithHttpInfo($errors, $limit, $remote, $running, $since, $start, $statusfilter, $typefilter, $until, $userfilter, $view, $contentType);
        return $response;
    }

    /**
     * Operation remotesTasksGetStatisticsWithHttpInfo
     *
     * Get task statistics for the specified filters
     *
     * @param  bool|null $errors Only list erroneous tasks. (optional, default to 0)
     * @param  int|null $limit Only list this amount of tasks. (0 means no limit) (optional, default to 50)
     * @param  string|null $remote Remote ID. (optional)
     * @param  bool|null $running Only list running tasks. (optional, default to 0)
     * @param  int|null $since Only list tasks since this UNIX epoch. (optional)
     * @param  int|null $start List tasks beginning from this offset. (optional, default to 0)
     * @param  \ClientApi\Pdm\Model\PdmStatusfilterEnum[]|null $statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param  string|null $typefilter Only list tasks whose type contains this. (optional)
     * @param  int|null $until Only list tasks until this UNIX epoch. (optional)
     * @param  string|null $userfilter Only list tasks from this user. (optional)
     * @param  string|null $view View name. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['remotesTasksGetStatistics'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pdm\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pdm\Model\RemotesTasksGetStatisticsResponse|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError, HTTP status code, HTTP response headers (array of strings)
     */
    public function remotesTasksGetStatisticsWithHttpInfo($errors = 0, $limit = 50, $remote = null, $running = 0, $since = null, $start = 0, $statusfilter = null, $typefilter = null, $until = null, $userfilter = null, $view = null, string $contentType = self::contentTypes['remotesTasksGetStatistics'][0])
    {
        $request = $this->remotesTasksGetStatisticsRequest($errors, $limit, $remote, $running, $since, $start, $statusfilter, $typefilter, $until, $userfilter, $view, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\RemotesTasksGetStatisticsResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pdm\Model\RemotesTasksGetStatisticsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\RemotesTasksGetStatisticsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation remotesTasksGetStatisticsAsync
     *
     * Get task statistics for the specified filters
     *
     * @param  bool|null $errors Only list erroneous tasks. (optional, default to 0)
     * @param  int|null $limit Only list this amount of tasks. (0 means no limit) (optional, default to 50)
     * @param  string|null $remote Remote ID. (optional)
     * @param  bool|null $running Only list running tasks. (optional, default to 0)
     * @param  int|null $since Only list tasks since this UNIX epoch. (optional)
     * @param  int|null $start List tasks beginning from this offset. (optional, default to 0)
     * @param  \ClientApi\Pdm\Model\PdmStatusfilterEnum[]|null $statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param  string|null $typefilter Only list tasks whose type contains this. (optional)
     * @param  int|null $until Only list tasks until this UNIX epoch. (optional)
     * @param  string|null $userfilter Only list tasks from this user. (optional)
     * @param  string|null $view View name. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['remotesTasksGetStatistics'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function remotesTasksGetStatisticsAsync($errors = 0, $limit = 50, $remote = null, $running = 0, $since = null, $start = 0, $statusfilter = null, $typefilter = null, $until = null, $userfilter = null, $view = null, string $contentType = self::contentTypes['remotesTasksGetStatistics'][0])
    {
        return $this->remotesTasksGetStatisticsAsyncWithHttpInfo($errors, $limit, $remote, $running, $since, $start, $statusfilter, $typefilter, $until, $userfilter, $view, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation remotesTasksGetStatisticsAsyncWithHttpInfo
     *
     * Get task statistics for the specified filters
     *
     * @param  bool|null $errors Only list erroneous tasks. (optional, default to 0)
     * @param  int|null $limit Only list this amount of tasks. (0 means no limit) (optional, default to 50)
     * @param  string|null $remote Remote ID. (optional)
     * @param  bool|null $running Only list running tasks. (optional, default to 0)
     * @param  int|null $since Only list tasks since this UNIX epoch. (optional)
     * @param  int|null $start List tasks beginning from this offset. (optional, default to 0)
     * @param  \ClientApi\Pdm\Model\PdmStatusfilterEnum[]|null $statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param  string|null $typefilter Only list tasks whose type contains this. (optional)
     * @param  int|null $until Only list tasks until this UNIX epoch. (optional)
     * @param  string|null $userfilter Only list tasks from this user. (optional)
     * @param  string|null $view View name. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['remotesTasksGetStatistics'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function remotesTasksGetStatisticsAsyncWithHttpInfo($errors = 0, $limit = 50, $remote = null, $running = 0, $since = null, $start = 0, $statusfilter = null, $typefilter = null, $until = null, $userfilter = null, $view = null, string $contentType = self::contentTypes['remotesTasksGetStatistics'][0])
    {
        $returnType = '\ClientApi\Pdm\Model\RemotesTasksGetStatisticsResponse';
        $request = $this->remotesTasksGetStatisticsRequest($errors, $limit, $remote, $running, $since, $start, $statusfilter, $typefilter, $until, $userfilter, $view, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'remotesTasksGetStatistics'
     *
     * @param  bool|null $errors Only list erroneous tasks. (optional, default to 0)
     * @param  int|null $limit Only list this amount of tasks. (0 means no limit) (optional, default to 50)
     * @param  string|null $remote Remote ID. (optional)
     * @param  bool|null $running Only list running tasks. (optional, default to 0)
     * @param  int|null $since Only list tasks since this UNIX epoch. (optional)
     * @param  int|null $start List tasks beginning from this offset. (optional, default to 0)
     * @param  \ClientApi\Pdm\Model\PdmStatusfilterEnum[]|null $statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param  string|null $typefilter Only list tasks whose type contains this. (optional)
     * @param  int|null $until Only list tasks until this UNIX epoch. (optional)
     * @param  string|null $userfilter Only list tasks from this user. (optional)
     * @param  string|null $view View name. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['remotesTasksGetStatistics'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function remotesTasksGetStatisticsRequest($errors = 0, $limit = 50, $remote = null, $running = 0, $since = null, $start = 0, $statusfilter = null, $typefilter = null, $until = null, $userfilter = null, $view = null, string $contentType = self::contentTypes['remotesTasksGetStatistics'][0])
    {



        if ($remote !== null && strlen($remote) > 32) {
            throw new \InvalidArgumentException('invalid length for "$remote" when calling RemotesTasksApi.remotesTasksGetStatistics, must be smaller than or equal to 32.');
        }
        if ($remote !== null && strlen($remote) < 2) {
            throw new \InvalidArgumentException('invalid length for "$remote" when calling RemotesTasksApi.remotesTasksGetStatistics, must be bigger than or equal to 2.');
        }
        if ($remote !== null && !preg_match("/^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/", $remote)) {
            throw new \InvalidArgumentException("invalid value for \"remote\" when calling RemotesTasksApi.remotesTasksGetStatistics, must conform to the pattern /^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/.");
        }
        







        if ($view !== null && strlen($view) > 32) {
            throw new \InvalidArgumentException('invalid length for "$view" when calling RemotesTasksApi.remotesTasksGetStatistics, must be smaller than or equal to 32.');
        }
        if ($view !== null && strlen($view) < 2) {
            throw new \InvalidArgumentException('invalid length for "$view" when calling RemotesTasksApi.remotesTasksGetStatistics, must be bigger than or equal to 2.');
        }
        if ($view !== null && !preg_match("/^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/", $view)) {
            throw new \InvalidArgumentException("invalid value for \"view\" when calling RemotesTasksApi.remotesTasksGetStatistics, must conform to the pattern /^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/.");
        }
        

        $resourcePath = '/remotes/tasks/statistics';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $errors,
            'errors', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $remote,
            'remote', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $running,
            'running', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $since,
            'since', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start,
            'start', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $statusfilter,
            'statusfilter', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $typefilter,
            'typefilter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $until,
            'until', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $userfilter,
            'userfilter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $view,
            'view', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation remotesTasksGetTasks
     *
     * Directory index
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['remotesTasksGetTasks'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pdm\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pdm\Model\RemotesTasksGetTasksResponse|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError
     */
    public function remotesTasksGetTasks(string $contentType = self::contentTypes['remotesTasksGetTasks'][0])
    {
        list($response) = $this->remotesTasksGetTasksWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation remotesTasksGetTasksWithHttpInfo
     *
     * Directory index
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['remotesTasksGetTasks'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pdm\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pdm\Model\RemotesTasksGetTasksResponse|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError|\ClientApi\Pdm\Model\PdmError, HTTP status code, HTTP response headers (array of strings)
     */
    public function remotesTasksGetTasksWithHttpInfo(string $contentType = self::contentTypes['remotesTasksGetTasks'][0])
    {
        $request = $this->remotesTasksGetTasksRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\RemotesTasksGetTasksResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pdm\Model\PdmError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pdm\Model\RemotesTasksGetTasksResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\RemotesTasksGetTasksResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pdm\Model\PdmError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation remotesTasksGetTasksAsync
     *
     * Directory index
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['remotesTasksGetTasks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function remotesTasksGetTasksAsync(string $contentType = self::contentTypes['remotesTasksGetTasks'][0])
    {
        return $this->remotesTasksGetTasksAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation remotesTasksGetTasksAsyncWithHttpInfo
     *
     * Directory index
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['remotesTasksGetTasks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function remotesTasksGetTasksAsyncWithHttpInfo(string $contentType = self::contentTypes['remotesTasksGetTasks'][0])
    {
        $returnType = '\ClientApi\Pdm\Model\RemotesTasksGetTasksResponse';
        $request = $this->remotesTasksGetTasksRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'remotesTasksGetTasks'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['remotesTasksGetTasks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function remotesTasksGetTasksRequest(string $contentType = self::contentTypes['remotesTasksGetTasks'][0])
    {


        $resourcePath = '/remotes/tasks';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
