<?php
/**
 * AccessAclGetAclResponseDataInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pdm\Model;

use \ArrayAccess;
use \ClientApi\Pdm\ObjectSerializer;

/**
 * AccessAclGetAclResponseDataInner Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AccessAclGetAclResponseDataInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'AccessAclGetAclResponse_data_inner';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'path' => 'string',
        'propagate' => 'bool',
        'roleid' => 'string',
        'ugid' => 'string',
        'ugid_type' => '\ClientApi\Pdm\Model\PdmAccessAclUgidTypeEnum',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'path' => null,
        'propagate' => null,
        'roleid' => null,
        'ugid' => null,
        'ugid_type' => null,
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'path' => false,
        'propagate' => false,
        'roleid' => false,
        'ugid' => false,
        'ugid_type' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'path' => 'path',
        'propagate' => 'propagate',
        'roleid' => 'roleid',
        'ugid' => 'ugid',
        'ugid_type' => 'ugid_type',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'path' => 'setPath',
        'propagate' => 'setPropagate',
        'roleid' => 'setRoleid',
        'ugid' => 'setUgid',
        'ugid_type' => 'setUgidType',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'path' => 'getPath',
        'propagate' => 'getPropagate',
        'roleid' => 'getRoleid',
        'ugid' => 'getUgid',
        'ugid_type' => 'getUgidType',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('path', $data ?? [], null);
        
        $this->setIfExists('propagate', $data ?? [], true);
        
        $this->setIfExists('roleid', $data ?? [], null);
        
        $this->setIfExists('ugid', $data ?? [], null);
        
        $this->setIfExists('ugid_type', $data ?? [], null);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        if ($this->container['path'] === null) {
            $invalidProperties[] = "'path' can't be null";
        }
        if ((mb_strlen($this->container['path']) > 128)) {
            $invalidProperties[] = "invalid value for 'path', the character length must be smaller than or equal to 128.";
        }

        if ((mb_strlen($this->container['path']) < 1)) {
            $invalidProperties[] = "invalid value for 'path', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^(?:/|(?:/(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*))+)$/", $this->container['path'])) {
            $invalidProperties[] = "invalid value for 'path', must be conform to the pattern /^(?:/|(?:/(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*))+)$/.";
        }

        
        if ($this->container['propagate'] === null) {
            $invalidProperties[] = "'propagate' can't be null";
        }
        
        if ($this->container['roleid'] === null) {
            $invalidProperties[] = "'roleid' can't be null";
        }
        
        if ($this->container['ugid'] === null) {
            $invalidProperties[] = "'ugid' can't be null";
        }
        
        if ($this->container['ugid_type'] === null) {
            $invalidProperties[] = "'ugid_type' can't be null";
        }
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets path
     *
     * @return string
     */
    public function getPath()
    {
        return $this->container['path'];
    }

    /**
     * Sets path
     *
     * @param string $path Access control path.
     *
     * @return self
     */
    public function setPath($path)
    {
        if (is_null($path)) {
            throw new \InvalidArgumentException('non-nullable path cannot be null');
        }
        if ((mb_strlen($path) > 128)) {
            throw new \InvalidArgumentException('invalid length for $path when calling AccessAclGetAclResponseDataInner., must be smaller than or equal to 128.');
        }
        if ((mb_strlen($path) < 1)) {
            throw new \InvalidArgumentException('invalid length for $path when calling AccessAclGetAclResponseDataInner., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^(?:/|(?:/(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*))+)$/", ObjectSerializer::toString($path)))) {
            throw new \InvalidArgumentException("invalid value for \$path when calling AccessAclGetAclResponseDataInner., must conform to the pattern /^(?:/|(?:/(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*))+)$/.");
        }

        $this->container['path'] = $path;

        return $this;
    }
    

    /**
     * Gets propagate
     *
     * @return bool
     */
    public function getPropagate()
    {
        return $this->container['propagate'];
    }

    /**
     * Sets propagate
     *
     * @param bool $propagate Allow to propagate (inherit) permissions.
     *
     * @return self
     */
    public function setPropagate($propagate)
    {
        if (is_null($propagate)) {
            throw new \InvalidArgumentException('non-nullable propagate cannot be null');
        }
        $this->container['propagate'] = $propagate;

        return $this;
    }
    

    /**
     * Gets roleid
     *
     * @return string
     */
    public function getRoleid()
    {
        return $this->container['roleid'];
    }

    /**
     * Sets roleid
     *
     * @param string $roleid A role represented as a string.
     *
     * @return self
     */
    public function setRoleid($roleid)
    {
        if (is_null($roleid)) {
            throw new \InvalidArgumentException('non-nullable roleid cannot be null');
        }
        $this->container['roleid'] = $roleid;

        return $this;
    }
    

    /**
     * Gets ugid
     *
     * @return string
     */
    public function getUgid()
    {
        return $this->container['ugid'];
    }

    /**
     * Sets ugid
     *
     * @param string $ugid User or Group ID.
     *
     * @return self
     */
    public function setUgid($ugid)
    {
        if (is_null($ugid)) {
            throw new \InvalidArgumentException('non-nullable ugid cannot be null');
        }
        $this->container['ugid'] = $ugid;

        return $this;
    }
    

    /**
     * Gets ugid_type
     *
     * @return \ClientApi\Pdm\Model\PdmAccessAclUgidTypeEnum
     */
    public function getUgidType()
    {
        return $this->container['ugid_type'];
    }

    /**
     * Sets ugid_type
     *
     * @param \ClientApi\Pdm\Model\PdmAccessAclUgidTypeEnum $ugid_type Type of the 'ugid' property in the ACL entry list.
     *
     * @return self
     */
    public function setUgidType($ugid_type)
    {
        if (is_null($ugid_type)) {
            throw new \InvalidArgumentException('non-nullable ugid_type cannot be null');
        }
        $this->container['ugid_type'] = $ugid_type;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



