<?php
/**
 * AccessAclUpdateAclRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pdm\Model;

use \ArrayAccess;
use \ClientApi\Pdm\ObjectSerializer;

/**
 * AccessAclUpdateAclRequest Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AccessAclUpdateAclRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'AccessAclUpdateAclRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'auth_id' => 'string',
        'delete' => 'bool',
        'digest' => 'string',
        'group' => 'string',
        'path' => 'string',
        'propagate' => 'bool',
        'role' => 'string',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'auth_id' => null,
        'delete' => null,
        'digest' => null,
        'group' => null,
        'path' => null,
        'propagate' => null,
        'role' => null,
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'auth_id' => false,
        'delete' => false,
        'digest' => false,
        'group' => false,
        'path' => false,
        'propagate' => false,
        'role' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'auth_id' => 'auth-id',
        'delete' => 'delete',
        'digest' => 'digest',
        'group' => 'group',
        'path' => 'path',
        'propagate' => 'propagate',
        'role' => 'role',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'auth_id' => 'setAuthId',
        'delete' => 'setDelete',
        'digest' => 'setDigest',
        'group' => 'setGroup',
        'path' => 'setPath',
        'propagate' => 'setPropagate',
        'role' => 'setRole',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'auth_id' => 'getAuthId',
        'delete' => 'getDelete',
        'digest' => 'getDigest',
        'group' => 'getGroup',
        'path' => 'getPath',
        'propagate' => 'getPropagate',
        'role' => 'getRole',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('auth_id', $data ?? [], null);
        
        $this->setIfExists('delete', $data ?? [], 0);
        
        $this->setIfExists('digest', $data ?? [], null);
        
        $this->setIfExists('group', $data ?? [], null);
        
        $this->setIfExists('path', $data ?? [], null);
        
        $this->setIfExists('propagate', $data ?? [], 1);
        
        $this->setIfExists('role', $data ?? [], null);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        if (!is_null($this->container['auth_id']) && (mb_strlen($this->container['auth_id']) > 64)) {
            $invalidProperties[] = "invalid value for 'auth_id', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['auth_id']) && (mb_strlen($this->container['auth_id']) < 3)) {
            $invalidProperties[] = "invalid value for 'auth_id', the character length must be bigger than or equal to 3.";
        }

        if (!is_null($this->container['auth_id']) && !preg_match("/^(?:(?:[^\\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)|(?:[^\\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)!(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*))$/", $this->container['auth_id'])) {
            $invalidProperties[] = "invalid value for 'auth_id', must be conform to the pattern /^(?:(?:[^\\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)|(?:[^\\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)!(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*))$/.";
        }

        
        
        if (!is_null($this->container['digest']) && !preg_match("/^[a-f0-9]{64}$/", $this->container['digest'])) {
            $invalidProperties[] = "invalid value for 'digest', must be conform to the pattern /^[a-f0-9]{64}$/.";
        }

        
        if (!is_null($this->container['group']) && (mb_strlen($this->container['group']) > 64)) {
            $invalidProperties[] = "invalid value for 'group', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['group']) && (mb_strlen($this->container['group']) < 3)) {
            $invalidProperties[] = "invalid value for 'group', the character length must be bigger than or equal to 3.";
        }

        if (!is_null($this->container['group']) && !preg_match("/^(?:[^\\s:/[:cntrl:]]+)$/", $this->container['group'])) {
            $invalidProperties[] = "invalid value for 'group', must be conform to the pattern /^(?:[^\\s:/[:cntrl:]]+)$/.";
        }

        
        if ($this->container['path'] === null) {
            $invalidProperties[] = "'path' can't be null";
        }
        if ((mb_strlen($this->container['path']) > 128)) {
            $invalidProperties[] = "invalid value for 'path', the character length must be smaller than or equal to 128.";
        }

        if ((mb_strlen($this->container['path']) < 1)) {
            $invalidProperties[] = "invalid value for 'path', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^(?:/|(?:/(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*))+)$/", $this->container['path'])) {
            $invalidProperties[] = "invalid value for 'path', must be conform to the pattern /^(?:/|(?:/(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*))+)$/.";
        }

        
        
        if ($this->container['role'] === null) {
            $invalidProperties[] = "'role' can't be null";
        }
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets auth_id
     *
     * @return string|null
     */
    public function getAuthId()
    {
        return $this->container['auth_id'];
    }

    /**
     * Sets auth_id
     *
     * @param string|null $auth_id Authentication ID
     *
     * @return self
     */
    public function setAuthId($auth_id)
    {
        if (is_null($auth_id)) {
            throw new \InvalidArgumentException('non-nullable auth_id cannot be null');
        }
        if ((mb_strlen($auth_id) > 64)) {
            throw new \InvalidArgumentException('invalid length for $auth_id when calling AccessAclUpdateAclRequest., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($auth_id) < 3)) {
            throw new \InvalidArgumentException('invalid length for $auth_id when calling AccessAclUpdateAclRequest., must be bigger than or equal to 3.');
        }
        if ((!preg_match("/^(?:(?:[^\\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)|(?:[^\\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)!(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*))$/", ObjectSerializer::toString($auth_id)))) {
            throw new \InvalidArgumentException("invalid value for \$auth_id when calling AccessAclUpdateAclRequest., must conform to the pattern /^(?:(?:[^\\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)|(?:[^\\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)!(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*))$/.");
        }

        $this->container['auth_id'] = $auth_id;

        return $this;
    }
    

    /**
     * Gets delete
     *
     * @return bool|null
     */
    public function getDelete()
    {
        return $this->container['delete'];
    }

    /**
     * Sets delete
     *
     * @param bool|null $delete Remove permissions (instead of adding it).
     *
     * @return self
     */
    public function setDelete($delete)
    {
        if (is_null($delete)) {
            throw new \InvalidArgumentException('non-nullable delete cannot be null');
        }
        $this->container['delete'] = $delete;

        return $this;
    }
    

    /**
     * Gets digest
     *
     * @return string|null
     */
    public function getDigest()
    {
        return $this->container['digest'];
    }

    /**
     * Sets digest
     *
     * @param string|null $digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
     *
     * @return self
     */
    public function setDigest($digest)
    {
        if (is_null($digest)) {
            throw new \InvalidArgumentException('non-nullable digest cannot be null');
        }

        if ((!preg_match("/^[a-f0-9]{64}$/", ObjectSerializer::toString($digest)))) {
            throw new \InvalidArgumentException("invalid value for \$digest when calling AccessAclUpdateAclRequest., must conform to the pattern /^[a-f0-9]{64}$/.");
        }

        $this->container['digest'] = $digest;

        return $this;
    }
    

    /**
     * Gets group
     *
     * @return string|null
     */
    public function getGroup()
    {
        return $this->container['group'];
    }

    /**
     * Sets group
     *
     * @param string|null $group Group ID
     *
     * @return self
     */
    public function setGroup($group)
    {
        if (is_null($group)) {
            throw new \InvalidArgumentException('non-nullable group cannot be null');
        }
        if ((mb_strlen($group) > 64)) {
            throw new \InvalidArgumentException('invalid length for $group when calling AccessAclUpdateAclRequest., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($group) < 3)) {
            throw new \InvalidArgumentException('invalid length for $group when calling AccessAclUpdateAclRequest., must be bigger than or equal to 3.');
        }
        if ((!preg_match("/^(?:[^\\s:/[:cntrl:]]+)$/", ObjectSerializer::toString($group)))) {
            throw new \InvalidArgumentException("invalid value for \$group when calling AccessAclUpdateAclRequest., must conform to the pattern /^(?:[^\\s:/[:cntrl:]]+)$/.");
        }

        $this->container['group'] = $group;

        return $this;
    }
    

    /**
     * Gets path
     *
     * @return string
     */
    public function getPath()
    {
        return $this->container['path'];
    }

    /**
     * Sets path
     *
     * @param string $path Access control path.
     *
     * @return self
     */
    public function setPath($path)
    {
        if (is_null($path)) {
            throw new \InvalidArgumentException('non-nullable path cannot be null');
        }
        if ((mb_strlen($path) > 128)) {
            throw new \InvalidArgumentException('invalid length for $path when calling AccessAclUpdateAclRequest., must be smaller than or equal to 128.');
        }
        if ((mb_strlen($path) < 1)) {
            throw new \InvalidArgumentException('invalid length for $path when calling AccessAclUpdateAclRequest., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^(?:/|(?:/(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*))+)$/", ObjectSerializer::toString($path)))) {
            throw new \InvalidArgumentException("invalid value for \$path when calling AccessAclUpdateAclRequest., must conform to the pattern /^(?:/|(?:/(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*))+)$/.");
        }

        $this->container['path'] = $path;

        return $this;
    }
    

    /**
     * Gets propagate
     *
     * @return bool|null
     */
    public function getPropagate()
    {
        return $this->container['propagate'];
    }

    /**
     * Sets propagate
     *
     * @param bool|null $propagate Allow to propagate (inherit) permissions.
     *
     * @return self
     */
    public function setPropagate($propagate)
    {
        if (is_null($propagate)) {
            throw new \InvalidArgumentException('non-nullable propagate cannot be null');
        }
        $this->container['propagate'] = $propagate;

        return $this;
    }
    

    /**
     * Gets role
     *
     * @return string
     */
    public function getRole()
    {
        return $this->container['role'];
    }

    /**
     * Sets role
     *
     * @param string $role Name of a role that the auth id will be granted.
     *
     * @return self
     */
    public function setRole($role)
    {
        if (is_null($role)) {
            throw new \InvalidArgumentException('non-nullable role cannot be null');
        }
        $this->container['role'] = $role;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



