<?php
/**
 * ConfigAccessUpdateOpenidRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pdm\Model;

use \ArrayAccess;
use \ClientApi\Pdm\ObjectSerializer;

/**
 * ConfigAccessUpdateOpenidRequest Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ConfigAccessUpdateOpenidRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ConfigAccessUpdateOpenidRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'acr_values' => '\ClientApi\Pdm\Model\PdmAcrValuesField',
        'autocreate' => 'bool',
        'client_id' => 'string',
        'client_key' => 'string',
        'comment' => 'string',
        'default' => 'bool',
        'delete' => '\ClientApi\Pdm\Model\PdmConfigAccessInlineEnum[]',
        'digest' => 'string',
        'issuer_url' => 'string',
        'prompt' => 'string',
        'scopes' => '\ClientApi\Pdm\Model\PdmScopesField',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'acr_values' => null,
        'autocreate' => null,
        'client_id' => null,
        'client_key' => null,
        'comment' => null,
        'default' => null,
        'delete' => null,
        'digest' => null,
        'issuer_url' => null,
        'prompt' => null,
        'scopes' => null,
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'acr_values' => false,
        'autocreate' => false,
        'client_id' => false,
        'client_key' => false,
        'comment' => false,
        'default' => false,
        'delete' => false,
        'digest' => false,
        'issuer_url' => false,
        'prompt' => false,
        'scopes' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'acr_values' => 'acr-values',
        'autocreate' => 'autocreate',
        'client_id' => 'client-id',
        'client_key' => 'client-key',
        'comment' => 'comment',
        'default' => 'default',
        'delete' => 'delete',
        'digest' => 'digest',
        'issuer_url' => 'issuer-url',
        'prompt' => 'prompt',
        'scopes' => 'scopes',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'acr_values' => 'setAcrValues',
        'autocreate' => 'setAutocreate',
        'client_id' => 'setClientId',
        'client_key' => 'setClientKey',
        'comment' => 'setComment',
        'default' => 'setDefault',
        'delete' => 'setDelete',
        'digest' => 'setDigest',
        'issuer_url' => 'setIssuerUrl',
        'prompt' => 'setPrompt',
        'scopes' => 'setScopes',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'acr_values' => 'getAcrValues',
        'autocreate' => 'getAutocreate',
        'client_id' => 'getClientId',
        'client_key' => 'getClientKey',
        'comment' => 'getComment',
        'default' => 'getDefault',
        'delete' => 'getDelete',
        'digest' => 'getDigest',
        'issuer_url' => 'getIssuerUrl',
        'prompt' => 'getPrompt',
        'scopes' => 'getScopes',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('acr_values', $data ?? [], null);
        
        $this->setIfExists('autocreate', $data ?? [], false);
        
        $this->setIfExists('client_id', $data ?? [], null);
        
        $this->setIfExists('client_key', $data ?? [], null);
        
        $this->setIfExists('comment', $data ?? [], null);
        
        $this->setIfExists('default', $data ?? [], null);
        
        $this->setIfExists('delete', $data ?? [], null);
        
        $this->setIfExists('digest', $data ?? [], null);
        
        $this->setIfExists('issuer_url', $data ?? [], null);
        
        $this->setIfExists('prompt', $data ?? [], null);
        
        $this->setIfExists('scopes', $data ?? [], null);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        
        
        
        
        if (!is_null($this->container['comment']) && (mb_strlen($this->container['comment']) > 128)) {
            $invalidProperties[] = "invalid value for 'comment', the character length must be smaller than or equal to 128.";
        }

        if (!is_null($this->container['comment']) && !preg_match("/^[[:^cntrl:]]*$/", $this->container['comment'])) {
            $invalidProperties[] = "invalid value for 'comment', must be conform to the pattern /^[[:^cntrl:]]*$/.";
        }

        
        
        
        if (!is_null($this->container['digest']) && !preg_match("/^[a-f0-9]{64}$/", $this->container['digest'])) {
            $invalidProperties[] = "invalid value for 'digest', must be conform to the pattern /^[a-f0-9]{64}$/.";
        }

        
        
        if (!is_null($this->container['prompt']) && !preg_match("/^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/", $this->container['prompt'])) {
            $invalidProperties[] = "invalid value for 'prompt', must be conform to the pattern /^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/.";
        }

        
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets acr_values
     *
     * @return \ClientApi\Pdm\Model\PdmAcrValuesField|null
     */
    public function getAcrValues()
    {
        return $this->container['acr_values'];
    }

    /**
     * Sets acr_values
     *
     * @param \ClientApi\Pdm\Model\PdmAcrValuesField|null $acr_values OpenID ACR List
     *
     * @return self
     */
    public function setAcrValues($acr_values)
    {
        if (is_null($acr_values)) {
            throw new \InvalidArgumentException('non-nullable acr_values cannot be null');
        }
        $this->container['acr_values'] = $acr_values;

        return $this;
    }
    

    /**
     * Gets autocreate
     *
     * @return bool|null
     */
    public function getAutocreate()
    {
        return $this->container['autocreate'];
    }

    /**
     * Sets autocreate
     *
     * @param bool|null $autocreate Automatically create users if they do not exist.
     *
     * @return self
     */
    public function setAutocreate($autocreate)
    {
        if (is_null($autocreate)) {
            throw new \InvalidArgumentException('non-nullable autocreate cannot be null');
        }
        $this->container['autocreate'] = $autocreate;

        return $this;
    }
    

    /**
     * Gets client_id
     *
     * @return string|null
     */
    public function getClientId()
    {
        return $this->container['client_id'];
    }

    /**
     * Sets client_id
     *
     * @param string|null $client_id OpenID Client ID
     *
     * @return self
     */
    public function setClientId($client_id)
    {
        if (is_null($client_id)) {
            throw new \InvalidArgumentException('non-nullable client_id cannot be null');
        }
        $this->container['client_id'] = $client_id;

        return $this;
    }
    

    /**
     * Gets client_key
     *
     * @return string|null
     */
    public function getClientKey()
    {
        return $this->container['client_key'];
    }

    /**
     * Sets client_key
     *
     * @param string|null $client_key OpenID Client Key
     *
     * @return self
     */
    public function setClientKey($client_key)
    {
        if (is_null($client_key)) {
            throw new \InvalidArgumentException('non-nullable client_key cannot be null');
        }
        $this->container['client_key'] = $client_key;

        return $this;
    }
    

    /**
     * Gets comment
     *
     * @return string|null
     */
    public function getComment()
    {
        return $this->container['comment'];
    }

    /**
     * Sets comment
     *
     * @param string|null $comment Comment.
     *
     * @return self
     */
    public function setComment($comment)
    {
        if (is_null($comment)) {
            throw new \InvalidArgumentException('non-nullable comment cannot be null');
        }
        if ((mb_strlen($comment) > 128)) {
            throw new \InvalidArgumentException('invalid length for $comment when calling ConfigAccessUpdateOpenidRequest., must be smaller than or equal to 128.');
        }
        if ((!preg_match("/^[[:^cntrl:]]*$/", ObjectSerializer::toString($comment)))) {
            throw new \InvalidArgumentException("invalid value for \$comment when calling ConfigAccessUpdateOpenidRequest., must conform to the pattern /^[[:^cntrl:]]*$/.");
        }

        $this->container['comment'] = $comment;

        return $this;
    }
    

    /**
     * Gets default
     *
     * @return bool|null
     */
    public function getDefault()
    {
        return $this->container['default'];
    }

    /**
     * Sets default
     *
     * @param bool|null $default True if you want this to be the default realm selected on login.
     *
     * @return self
     */
    public function setDefault($default)
    {
        if (is_null($default)) {
            throw new \InvalidArgumentException('non-nullable default cannot be null');
        }
        $this->container['default'] = $default;

        return $this;
    }
    

    /**
     * Gets delete
     *
     * @return \ClientApi\Pdm\Model\PdmConfigAccessInlineEnum[]|null
     */
    public function getDelete()
    {
        return $this->container['delete'];
    }

    /**
     * Sets delete
     *
     * @param \ClientApi\Pdm\Model\PdmConfigAccessInlineEnum[]|null $delete List of properties to delete.
     *
     * @return self
     */
    public function setDelete($delete)
    {
        if (is_null($delete)) {
            throw new \InvalidArgumentException('non-nullable delete cannot be null');
        }
        $this->container['delete'] = $delete;

        return $this;
    }
    

    /**
     * Gets digest
     *
     * @return string|null
     */
    public function getDigest()
    {
        return $this->container['digest'];
    }

    /**
     * Sets digest
     *
     * @param string|null $digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
     *
     * @return self
     */
    public function setDigest($digest)
    {
        if (is_null($digest)) {
            throw new \InvalidArgumentException('non-nullable digest cannot be null');
        }

        if ((!preg_match("/^[a-f0-9]{64}$/", ObjectSerializer::toString($digest)))) {
            throw new \InvalidArgumentException("invalid value for \$digest when calling ConfigAccessUpdateOpenidRequest., must conform to the pattern /^[a-f0-9]{64}$/.");
        }

        $this->container['digest'] = $digest;

        return $this;
    }
    

    /**
     * Gets issuer_url
     *
     * @return string|null
     */
    public function getIssuerUrl()
    {
        return $this->container['issuer_url'];
    }

    /**
     * Sets issuer_url
     *
     * @param string|null $issuer_url OpenID Issuer Url
     *
     * @return self
     */
    public function setIssuerUrl($issuer_url)
    {
        if (is_null($issuer_url)) {
            throw new \InvalidArgumentException('non-nullable issuer_url cannot be null');
        }
        $this->container['issuer_url'] = $issuer_url;

        return $this;
    }
    

    /**
     * Gets prompt
     *
     * @return string|null
     */
    public function getPrompt()
    {
        return $this->container['prompt'];
    }

    /**
     * Sets prompt
     *
     * @param string|null $prompt OpenID Prompt
     *
     * @return self
     */
    public function setPrompt($prompt)
    {
        if (is_null($prompt)) {
            throw new \InvalidArgumentException('non-nullable prompt cannot be null');
        }

        if ((!preg_match("/^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/", ObjectSerializer::toString($prompt)))) {
            throw new \InvalidArgumentException("invalid value for \$prompt when calling ConfigAccessUpdateOpenidRequest., must conform to the pattern /^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/.");
        }

        $this->container['prompt'] = $prompt;

        return $this;
    }
    

    /**
     * Gets scopes
     *
     * @return \ClientApi\Pdm\Model\PdmScopesField|null
     */
    public function getScopes()
    {
        return $this->container['scopes'];
    }

    /**
     * Sets scopes
     *
     * @param \ClientApi\Pdm\Model\PdmScopesField|null $scopes OpenID Scope List
     *
     * @return self
     */
    public function setScopes($scopes)
    {
        if (is_null($scopes)) {
            throw new \InvalidArgumentException('non-nullable scopes cannot be null');
        }
        $this->container['scopes'] = $scopes;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



