<?php
/**
 * NodesStatusGetStatusResponseData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pdm\Model;

use \ArrayAccess;
use \ClientApi\Pdm\ObjectSerializer;

/**
 * NodesStatusGetStatusResponseData Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NodesStatusGetStatusResponseData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'NodesStatusGetStatusResponse_data';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'boot_info' => '\ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataBootInfo',
        'cpu' => 'float',
        'cpuinfo' => '\ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataCpuinfo',
        'current_kernel' => '\ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataCurrentKernel',
        'info' => '\ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataInfo',
        'kversion' => 'string',
        'loadavg' => 'float[]',
        'memory' => '\ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataMemory',
        'root' => '\ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataRoot',
        'swap' => '\ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataSwap',
        'uptime' => 'int',
        'wait' => 'float',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'boot_info' => null,
        'cpu' => null,
        'cpuinfo' => null,
        'current_kernel' => null,
        'info' => null,
        'kversion' => null,
        'loadavg' => null,
        'memory' => null,
        'root' => null,
        'swap' => null,
        'uptime' => 'int64',
        'wait' => null,
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'boot_info' => false,
        'cpu' => false,
        'cpuinfo' => false,
        'current_kernel' => false,
        'info' => false,
        'kversion' => false,
        'loadavg' => false,
        'memory' => false,
        'root' => false,
        'swap' => false,
        'uptime' => false,
        'wait' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'boot_info' => 'boot-info',
        'cpu' => 'cpu',
        'cpuinfo' => 'cpuinfo',
        'current_kernel' => 'current-kernel',
        'info' => 'info',
        'kversion' => 'kversion',
        'loadavg' => 'loadavg',
        'memory' => 'memory',
        'root' => 'root',
        'swap' => 'swap',
        'uptime' => 'uptime',
        'wait' => 'wait',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'boot_info' => 'setBootInfo',
        'cpu' => 'setCpu',
        'cpuinfo' => 'setCpuinfo',
        'current_kernel' => 'setCurrentKernel',
        'info' => 'setInfo',
        'kversion' => 'setKversion',
        'loadavg' => 'setLoadavg',
        'memory' => 'setMemory',
        'root' => 'setRoot',
        'swap' => 'setSwap',
        'uptime' => 'setUptime',
        'wait' => 'setWait',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'boot_info' => 'getBootInfo',
        'cpu' => 'getCpu',
        'cpuinfo' => 'getCpuinfo',
        'current_kernel' => 'getCurrentKernel',
        'info' => 'getInfo',
        'kversion' => 'getKversion',
        'loadavg' => 'getLoadavg',
        'memory' => 'getMemory',
        'root' => 'getRoot',
        'swap' => 'getSwap',
        'uptime' => 'getUptime',
        'wait' => 'getWait',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('boot_info', $data ?? [], null);
        
        $this->setIfExists('cpu', $data ?? [], null);
        
        $this->setIfExists('cpuinfo', $data ?? [], null);
        
        $this->setIfExists('current_kernel', $data ?? [], null);
        
        $this->setIfExists('info', $data ?? [], null);
        
        $this->setIfExists('kversion', $data ?? [], null);
        
        $this->setIfExists('loadavg', $data ?? [], null);
        
        $this->setIfExists('memory', $data ?? [], null);
        
        $this->setIfExists('root', $data ?? [], null);
        
        $this->setIfExists('swap', $data ?? [], null);
        
        $this->setIfExists('uptime', $data ?? [], null);
        
        $this->setIfExists('wait', $data ?? [], null);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        if ($this->container['boot_info'] === null) {
            $invalidProperties[] = "'boot_info' can't be null";
        }
        
        if ($this->container['cpu'] === null) {
            $invalidProperties[] = "'cpu' can't be null";
        }
        
        if ($this->container['cpuinfo'] === null) {
            $invalidProperties[] = "'cpuinfo' can't be null";
        }
        
        if ($this->container['current_kernel'] === null) {
            $invalidProperties[] = "'current_kernel' can't be null";
        }
        
        if ($this->container['info'] === null) {
            $invalidProperties[] = "'info' can't be null";
        }
        
        if ($this->container['kversion'] === null) {
            $invalidProperties[] = "'kversion' can't be null";
        }
        
        if ($this->container['loadavg'] === null) {
            $invalidProperties[] = "'loadavg' can't be null";
        }
        
        if ($this->container['memory'] === null) {
            $invalidProperties[] = "'memory' can't be null";
        }
        
        if ($this->container['root'] === null) {
            $invalidProperties[] = "'root' can't be null";
        }
        
        if ($this->container['swap'] === null) {
            $invalidProperties[] = "'swap' can't be null";
        }
        
        if ($this->container['uptime'] === null) {
            $invalidProperties[] = "'uptime' can't be null";
        }
        if (($this->container['uptime'] < 0)) {
            $invalidProperties[] = "invalid value for 'uptime', must be bigger than or equal to 0.";
        }

        
        if ($this->container['wait'] === null) {
            $invalidProperties[] = "'wait' can't be null";
        }
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets boot_info
     *
     * @return \ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataBootInfo
     */
    public function getBootInfo()
    {
        return $this->container['boot_info'];
    }

    /**
     * Sets boot_info
     *
     * @param \ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataBootInfo $boot_info boot_info
     *
     * @return self
     */
    public function setBootInfo($boot_info)
    {
        if (is_null($boot_info)) {
            throw new \InvalidArgumentException('non-nullable boot_info cannot be null');
        }
        $this->container['boot_info'] = $boot_info;

        return $this;
    }
    

    /**
     * Gets cpu
     *
     * @return float
     */
    public function getCpu()
    {
        return $this->container['cpu'];
    }

    /**
     * Sets cpu
     *
     * @param float $cpu Total CPU usage since last query.
     *
     * @return self
     */
    public function setCpu($cpu)
    {
        if (is_null($cpu)) {
            throw new \InvalidArgumentException('non-nullable cpu cannot be null');
        }
        $this->container['cpu'] = $cpu;

        return $this;
    }
    

    /**
     * Gets cpuinfo
     *
     * @return \ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataCpuinfo
     */
    public function getCpuinfo()
    {
        return $this->container['cpuinfo'];
    }

    /**
     * Sets cpuinfo
     *
     * @param \ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataCpuinfo $cpuinfo cpuinfo
     *
     * @return self
     */
    public function setCpuinfo($cpuinfo)
    {
        if (is_null($cpuinfo)) {
            throw new \InvalidArgumentException('non-nullable cpuinfo cannot be null');
        }
        $this->container['cpuinfo'] = $cpuinfo;

        return $this;
    }
    

    /**
     * Gets current_kernel
     *
     * @return \ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataCurrentKernel
     */
    public function getCurrentKernel()
    {
        return $this->container['current_kernel'];
    }

    /**
     * Sets current_kernel
     *
     * @param \ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataCurrentKernel $current_kernel current_kernel
     *
     * @return self
     */
    public function setCurrentKernel($current_kernel)
    {
        if (is_null($current_kernel)) {
            throw new \InvalidArgumentException('non-nullable current_kernel cannot be null');
        }
        $this->container['current_kernel'] = $current_kernel;

        return $this;
    }
    

    /**
     * Gets info
     *
     * @return \ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataInfo
     */
    public function getInfo()
    {
        return $this->container['info'];
    }

    /**
     * Sets info
     *
     * @param \ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataInfo $info info
     *
     * @return self
     */
    public function setInfo($info)
    {
        if (is_null($info)) {
            throw new \InvalidArgumentException('non-nullable info cannot be null');
        }
        $this->container['info'] = $info;

        return $this;
    }
    

    /**
     * Gets kversion
     *
     * @return string
     */
    public function getKversion()
    {
        return $this->container['kversion'];
    }

    /**
     * Sets kversion
     *
     * @param string $kversion The current kernel version (LEGACY string type).
     *
     * @return self
     */
    public function setKversion($kversion)
    {
        if (is_null($kversion)) {
            throw new \InvalidArgumentException('non-nullable kversion cannot be null');
        }
        $this->container['kversion'] = $kversion;

        return $this;
    }
    

    /**
     * Gets loadavg
     *
     * @return float[]
     */
    public function getLoadavg()
    {
        return $this->container['loadavg'];
    }

    /**
     * Sets loadavg
     *
     * @param float[] $loadavg Load for 1, 5 and 15 minutes.
     *
     * @return self
     */
    public function setLoadavg($loadavg)
    {
        if (is_null($loadavg)) {
            throw new \InvalidArgumentException('non-nullable loadavg cannot be null');
        }
        $this->container['loadavg'] = $loadavg;

        return $this;
    }
    

    /**
     * Gets memory
     *
     * @return \ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataMemory
     */
    public function getMemory()
    {
        return $this->container['memory'];
    }

    /**
     * Sets memory
     *
     * @param \ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataMemory $memory memory
     *
     * @return self
     */
    public function setMemory($memory)
    {
        if (is_null($memory)) {
            throw new \InvalidArgumentException('non-nullable memory cannot be null');
        }
        $this->container['memory'] = $memory;

        return $this;
    }
    

    /**
     * Gets root
     *
     * @return \ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataRoot
     */
    public function getRoot()
    {
        return $this->container['root'];
    }

    /**
     * Sets root
     *
     * @param \ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataRoot $root root
     *
     * @return self
     */
    public function setRoot($root)
    {
        if (is_null($root)) {
            throw new \InvalidArgumentException('non-nullable root cannot be null');
        }
        $this->container['root'] = $root;

        return $this;
    }
    

    /**
     * Gets swap
     *
     * @return \ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataSwap
     */
    public function getSwap()
    {
        return $this->container['swap'];
    }

    /**
     * Sets swap
     *
     * @param \ClientApi\Pdm\Model\NodesStatusGetStatusResponseDataSwap $swap swap
     *
     * @return self
     */
    public function setSwap($swap)
    {
        if (is_null($swap)) {
            throw new \InvalidArgumentException('non-nullable swap cannot be null');
        }
        $this->container['swap'] = $swap;

        return $this;
    }
    

    /**
     * Gets uptime
     *
     * @return int
     */
    public function getUptime()
    {
        return $this->container['uptime'];
    }

    /**
     * Sets uptime
     *
     * @param int $uptime The current uptime of the server.
     *
     * @return self
     */
    public function setUptime($uptime)
    {
        if (is_null($uptime)) {
            throw new \InvalidArgumentException('non-nullable uptime cannot be null');
        }

        if (($uptime < 0)) {
            throw new \InvalidArgumentException('invalid value for $uptime when calling NodesStatusGetStatusResponseData., must be bigger than or equal to 0.');
        }

        $this->container['uptime'] = $uptime;

        return $this;
    }
    

    /**
     * Gets wait
     *
     * @return float
     */
    public function getWait()
    {
        return $this->container['wait'];
    }

    /**
     * Sets wait
     *
     * @param float $wait Total IO wait since last query.
     *
     * @return self
     */
    public function setWait($wait)
    {
        if (is_null($wait)) {
            throw new \InvalidArgumentException('non-nullable wait cannot be null');
        }
        $this->container['wait'] = $wait;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



