<?php
/**
 * NodesConfigUpdateConfigRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pdm\Model;

use \ArrayAccess;
use \ClientApi\Pdm\ObjectSerializer;

/**
 * NodesConfigUpdateConfigRequest Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NodesConfigUpdateConfigRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'NodesConfigUpdateConfigRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'ciphers_tls_1_2' => 'string',
        'ciphers_tls_1_3' => 'string',
        'default_lang' => '\ClientApi\Pdm\Model\PdmDefaultLangEnum',
        'delete' => '\ClientApi\Pdm\Model\PdmNodesConfigInlineEnum[]',
        'digest' => 'string',
        'email_from' => 'string',
        'http_proxy' => 'string',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'ciphers_tls_1_2' => null,
        'ciphers_tls_1_3' => null,
        'default_lang' => null,
        'delete' => null,
        'digest' => null,
        'email_from' => null,
        'http_proxy' => null,
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'ciphers_tls_1_2' => false,
        'ciphers_tls_1_3' => false,
        'default_lang' => false,
        'delete' => false,
        'digest' => false,
        'email_from' => false,
        'http_proxy' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ciphers_tls_1_2' => 'ciphers-tls-1.2',
        'ciphers_tls_1_3' => 'ciphers-tls-1.3',
        'default_lang' => 'default-lang',
        'delete' => 'delete',
        'digest' => 'digest',
        'email_from' => 'email-from',
        'http_proxy' => 'http-proxy',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ciphers_tls_1_2' => 'setCiphersTls12',
        'ciphers_tls_1_3' => 'setCiphersTls13',
        'default_lang' => 'setDefaultLang',
        'delete' => 'setDelete',
        'digest' => 'setDigest',
        'email_from' => 'setEmailFrom',
        'http_proxy' => 'setHttpProxy',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ciphers_tls_1_2' => 'getCiphersTls12',
        'ciphers_tls_1_3' => 'getCiphersTls13',
        'default_lang' => 'getDefaultLang',
        'delete' => 'getDelete',
        'digest' => 'getDigest',
        'email_from' => 'getEmailFrom',
        'http_proxy' => 'getHttpProxy',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('ciphers_tls_1_2', $data ?? [], null);
        
        $this->setIfExists('ciphers_tls_1_3', $data ?? [], null);
        
        $this->setIfExists('default_lang', $data ?? [], null);
        
        $this->setIfExists('delete', $data ?? [], null);
        
        $this->setIfExists('digest', $data ?? [], null);
        
        $this->setIfExists('email_from', $data ?? [], null);
        
        $this->setIfExists('http_proxy', $data ?? [], null);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        if (!is_null($this->container['ciphers_tls_1_2']) && !preg_match("/^[0-9A-Za-z_:, +!\\-@=.]+$/", $this->container['ciphers_tls_1_2'])) {
            $invalidProperties[] = "invalid value for 'ciphers_tls_1_2', must be conform to the pattern /^[0-9A-Za-z_:, +!\\-@=.]+$/.";
        }

        
        if (!is_null($this->container['ciphers_tls_1_3']) && !preg_match("/^[0-9A-Za-z_:, +!\\-@=.]+$/", $this->container['ciphers_tls_1_3'])) {
            $invalidProperties[] = "invalid value for 'ciphers_tls_1_3', must be conform to the pattern /^[0-9A-Za-z_:, +!\\-@=.]+$/.";
        }

        
        
        
        if (!is_null($this->container['digest']) && !preg_match("/^[a-f0-9]{64}$/", $this->container['digest'])) {
            $invalidProperties[] = "invalid value for 'digest', must be conform to the pattern /^[a-f0-9]{64}$/.";
        }

        
        if (!is_null($this->container['email_from']) && (mb_strlen($this->container['email_from']) > 64)) {
            $invalidProperties[] = "invalid value for 'email_from', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['email_from']) && (mb_strlen($this->container['email_from']) < 2)) {
            $invalidProperties[] = "invalid value for 'email_from', the character length must be bigger than or equal to 2.";
        }

        if (!is_null($this->container['email_from']) && !preg_match("/^[[:^cntrl:]]*$/", $this->container['email_from'])) {
            $invalidProperties[] = "invalid value for 'email_from', must be conform to the pattern /^[[:^cntrl:]]*$/.";
        }

        
        if (!is_null($this->container['http_proxy']) && (mb_strlen($this->container['http_proxy']) > 128)) {
            $invalidProperties[] = "invalid value for 'http_proxy', the character length must be smaller than or equal to 128.";
        }

        if (!is_null($this->container['http_proxy']) && (mb_strlen($this->container['http_proxy']) < 1)) {
            $invalidProperties[] = "invalid value for 'http_proxy', the character length must be bigger than or equal to 1.";
        }

        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets ciphers_tls_1_2
     *
     * @return string|null
     */
    public function getCiphersTls12()
    {
        return $this->container['ciphers_tls_1_2'];
    }

    /**
     * Sets ciphers_tls_1_2
     *
     * @param string|null $ciphers_tls_1_2 OpenSSL cipher list used by the api server for TLS <= 1.2
     *
     * @return self
     */
    public function setCiphersTls12($ciphers_tls_1_2)
    {
        if (is_null($ciphers_tls_1_2)) {
            throw new \InvalidArgumentException('non-nullable ciphers_tls_1_2 cannot be null');
        }

        if ((!preg_match("/^[0-9A-Za-z_:, +!\\-@=.]+$/", ObjectSerializer::toString($ciphers_tls_1_2)))) {
            throw new \InvalidArgumentException("invalid value for \$ciphers_tls_1_2 when calling NodesConfigUpdateConfigRequest., must conform to the pattern /^[0-9A-Za-z_:, +!\\-@=.]+$/.");
        }

        $this->container['ciphers_tls_1_2'] = $ciphers_tls_1_2;

        return $this;
    }
    

    /**
     * Gets ciphers_tls_1_3
     *
     * @return string|null
     */
    public function getCiphersTls13()
    {
        return $this->container['ciphers_tls_1_3'];
    }

    /**
     * Sets ciphers_tls_1_3
     *
     * @param string|null $ciphers_tls_1_3 OpenSSL ciphersuites list used by the api server for TLS 1.3
     *
     * @return self
     */
    public function setCiphersTls13($ciphers_tls_1_3)
    {
        if (is_null($ciphers_tls_1_3)) {
            throw new \InvalidArgumentException('non-nullable ciphers_tls_1_3 cannot be null');
        }

        if ((!preg_match("/^[0-9A-Za-z_:, +!\\-@=.]+$/", ObjectSerializer::toString($ciphers_tls_1_3)))) {
            throw new \InvalidArgumentException("invalid value for \$ciphers_tls_1_3 when calling NodesConfigUpdateConfigRequest., must conform to the pattern /^[0-9A-Za-z_:, +!\\-@=.]+$/.");
        }

        $this->container['ciphers_tls_1_3'] = $ciphers_tls_1_3;

        return $this;
    }
    

    /**
     * Gets default_lang
     *
     * @return \ClientApi\Pdm\Model\PdmDefaultLangEnum|null
     */
    public function getDefaultLang()
    {
        return $this->container['default_lang'];
    }

    /**
     * Sets default_lang
     *
     * @param \ClientApi\Pdm\Model\PdmDefaultLangEnum|null $default_lang All available languages in Proxmox. Taken from proxmox-i18n repository. pt_BR, zh_CN, and zh_TW use the same case in the translation files.
     *
     * @return self
     */
    public function setDefaultLang($default_lang)
    {
        if (is_null($default_lang)) {
            throw new \InvalidArgumentException('non-nullable default_lang cannot be null');
        }
        $this->container['default_lang'] = $default_lang;

        return $this;
    }
    

    /**
     * Gets delete
     *
     * @return \ClientApi\Pdm\Model\PdmNodesConfigInlineEnum[]|null
     */
    public function getDelete()
    {
        return $this->container['delete'];
    }

    /**
     * Sets delete
     *
     * @param \ClientApi\Pdm\Model\PdmNodesConfigInlineEnum[]|null $delete List of properties to delete.
     *
     * @return self
     */
    public function setDelete($delete)
    {
        if (is_null($delete)) {
            throw new \InvalidArgumentException('non-nullable delete cannot be null');
        }
        $this->container['delete'] = $delete;

        return $this;
    }
    

    /**
     * Gets digest
     *
     * @return string|null
     */
    public function getDigest()
    {
        return $this->container['digest'];
    }

    /**
     * Sets digest
     *
     * @param string|null $digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
     *
     * @return self
     */
    public function setDigest($digest)
    {
        if (is_null($digest)) {
            throw new \InvalidArgumentException('non-nullable digest cannot be null');
        }

        if ((!preg_match("/^[a-f0-9]{64}$/", ObjectSerializer::toString($digest)))) {
            throw new \InvalidArgumentException("invalid value for \$digest when calling NodesConfigUpdateConfigRequest., must conform to the pattern /^[a-f0-9]{64}$/.");
        }

        $this->container['digest'] = $digest;

        return $this;
    }
    

    /**
     * Gets email_from
     *
     * @return string|null
     */
    public function getEmailFrom()
    {
        return $this->container['email_from'];
    }

    /**
     * Sets email_from
     *
     * @param string|null $email_from E-Mail Address.
     *
     * @return self
     */
    public function setEmailFrom($email_from)
    {
        if (is_null($email_from)) {
            throw new \InvalidArgumentException('non-nullable email_from cannot be null');
        }
        if ((mb_strlen($email_from) > 64)) {
            throw new \InvalidArgumentException('invalid length for $email_from when calling NodesConfigUpdateConfigRequest., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($email_from) < 2)) {
            throw new \InvalidArgumentException('invalid length for $email_from when calling NodesConfigUpdateConfigRequest., must be bigger than or equal to 2.');
        }
        if ((!preg_match("/^[[:^cntrl:]]*$/", ObjectSerializer::toString($email_from)))) {
            throw new \InvalidArgumentException("invalid value for \$email_from when calling NodesConfigUpdateConfigRequest., must conform to the pattern /^[[:^cntrl:]]*$/.");
        }

        $this->container['email_from'] = $email_from;

        return $this;
    }
    

    /**
     * Gets http_proxy
     *
     * @return string|null
     */
    public function getHttpProxy()
    {
        return $this->container['http_proxy'];
    }

    /**
     * Sets http_proxy
     *
     * @param string|null $http_proxy HTTP proxy configuration [http://]<host>[:port]
     *
     * @return self
     */
    public function setHttpProxy($http_proxy)
    {
        if (is_null($http_proxy)) {
            throw new \InvalidArgumentException('non-nullable http_proxy cannot be null');
        }
        if ((mb_strlen($http_proxy) > 128)) {
            throw new \InvalidArgumentException('invalid length for $http_proxy when calling NodesConfigUpdateConfigRequest., must be smaller than or equal to 128.');
        }
        if ((mb_strlen($http_proxy) < 1)) {
            throw new \InvalidArgumentException('invalid length for $http_proxy when calling NodesConfigUpdateConfigRequest., must be bigger than or equal to 1.');
        }

        $this->container['http_proxy'] = $http_proxy;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



