<?php
/**
 * PbsRemotesGetRrddataResponseDataInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pdm\Model;

use \ArrayAccess;
use \ClientApi\Pdm\ObjectSerializer;

/**
 * PbsRemotesGetRrddataResponseDataInner Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PbsRemotesGetRrddataResponseDataInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PbsRemotesGetRrddataResponse_data_inner';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'disk_available' => 'float',
        'disk_read' => 'float',
        'disk_total' => 'float',
        'disk_used' => 'float',
        'disk_write' => 'float',
        'time' => 'int',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'disk_available' => null,
        'disk_read' => null,
        'disk_total' => null,
        'disk_used' => null,
        'disk_write' => null,
        'time' => 'int64',
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'disk_available' => false,
        'disk_read' => false,
        'disk_total' => false,
        'disk_used' => false,
        'disk_write' => false,
        'time' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'disk_available' => 'disk-available',
        'disk_read' => 'disk-read',
        'disk_total' => 'disk-total',
        'disk_used' => 'disk-used',
        'disk_write' => 'disk-write',
        'time' => 'time',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'disk_available' => 'setDiskAvailable',
        'disk_read' => 'setDiskRead',
        'disk_total' => 'setDiskTotal',
        'disk_used' => 'setDiskUsed',
        'disk_write' => 'setDiskWrite',
        'time' => 'setTime',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'disk_available' => 'getDiskAvailable',
        'disk_read' => 'getDiskRead',
        'disk_total' => 'getDiskTotal',
        'disk_used' => 'getDiskUsed',
        'disk_write' => 'getDiskWrite',
        'time' => 'getTime',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('disk_available', $data ?? [], null);
        
        $this->setIfExists('disk_read', $data ?? [], null);
        
        $this->setIfExists('disk_total', $data ?? [], null);
        
        $this->setIfExists('disk_used', $data ?? [], null);
        
        $this->setIfExists('disk_write', $data ?? [], null);
        
        $this->setIfExists('time', $data ?? [], null);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        
        
        
        
        
        if ($this->container['time'] === null) {
            $invalidProperties[] = "'time' can't be null";
        }
        if (($this->container['time'] < 0)) {
            $invalidProperties[] = "invalid value for 'time', must be bigger than or equal to 0.";
        }

        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets disk_available
     *
     * @return float|null
     */
    public function getDiskAvailable()
    {
        return $this->container['disk_available'];
    }

    /**
     * Sets disk_available
     *
     * @param float|null $disk_available Available disk space
     *
     * @return self
     */
    public function setDiskAvailable($disk_available)
    {
        if (is_null($disk_available)) {
            throw new \InvalidArgumentException('non-nullable disk_available cannot be null');
        }
        $this->container['disk_available'] = $disk_available;

        return $this;
    }
    

    /**
     * Gets disk_read
     *
     * @return float|null
     */
    public function getDiskRead()
    {
        return $this->container['disk_read'];
    }

    /**
     * Sets disk_read
     *
     * @param float|null $disk_read Disk read rate
     *
     * @return self
     */
    public function setDiskRead($disk_read)
    {
        if (is_null($disk_read)) {
            throw new \InvalidArgumentException('non-nullable disk_read cannot be null');
        }
        $this->container['disk_read'] = $disk_read;

        return $this;
    }
    

    /**
     * Gets disk_total
     *
     * @return float|null
     */
    public function getDiskTotal()
    {
        return $this->container['disk_total'];
    }

    /**
     * Sets disk_total
     *
     * @param float|null $disk_total Total disk size
     *
     * @return self
     */
    public function setDiskTotal($disk_total)
    {
        if (is_null($disk_total)) {
            throw new \InvalidArgumentException('non-nullable disk_total cannot be null');
        }
        $this->container['disk_total'] = $disk_total;

        return $this;
    }
    

    /**
     * Gets disk_used
     *
     * @return float|null
     */
    public function getDiskUsed()
    {
        return $this->container['disk_used'];
    }

    /**
     * Sets disk_used
     *
     * @param float|null $disk_used Disk utiliziation
     *
     * @return self
     */
    public function setDiskUsed($disk_used)
    {
        if (is_null($disk_used)) {
            throw new \InvalidArgumentException('non-nullable disk_used cannot be null');
        }
        $this->container['disk_used'] = $disk_used;

        return $this;
    }
    

    /**
     * Gets disk_write
     *
     * @return float|null
     */
    public function getDiskWrite()
    {
        return $this->container['disk_write'];
    }

    /**
     * Sets disk_write
     *
     * @param float|null $disk_write Disk write rate
     *
     * @return self
     */
    public function setDiskWrite($disk_write)
    {
        if (is_null($disk_write)) {
            throw new \InvalidArgumentException('non-nullable disk_write cannot be null');
        }
        $this->container['disk_write'] = $disk_write;

        return $this;
    }
    

    /**
     * Gets time
     *
     * @return int
     */
    public function getTime()
    {
        return $this->container['time'];
    }

    /**
     * Sets time
     *
     * @param int $time Timestamp (UNIX epoch)
     *
     * @return self
     */
    public function setTime($time)
    {
        if (is_null($time)) {
            throw new \InvalidArgumentException('non-nullable time cannot be null');
        }

        if (($time < 0)) {
            throw new \InvalidArgumentException('invalid value for $time when calling PbsRemotesGetRrddataResponseDataInner., must be bigger than or equal to 0.');
        }

        $this->container['time'] = $time;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



