<?php
/**
 * PdmBondModeEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pdm\Model;
use \ClientApi\Pdm\ObjectSerializer;

/**
 * PdmBondModeEnum Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PdmBondModeEnum
{
    /**
     * Possible values of this enum
     */
    public const BALANCE_RR = 'balance-rr';

    public const ACTIVE_BACKUP = 'active-backup';

    public const BALANCE_XOR = 'balance-xor';

    public const BROADCAST = 'broadcast';

    public const _802_3AD = '802.3ad';

    public const BALANCE_TLB = 'balance-tlb';

    public const BALANCE_ALB = 'balance-alb';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BALANCE_RR,
            self::ACTIVE_BACKUP,
            self::BALANCE_XOR,
            self::BROADCAST,
            self::_802_3AD,
            self::BALANCE_TLB,
            self::BALANCE_ALB
        ];
    }
}


