<?php
/**
 * PdmConfigCertificateInlineEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pdm\Model;
use \ClientApi\Pdm\ObjectSerializer;

/**
 * PdmConfigCertificateInlineEnum Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PdmConfigCertificateInlineEnum
{
    /**
     * Possible values of this enum
     */
    public const ACME = 'acme';

    public const ACMEDOMAIN0 = 'acmedomain0';

    public const ACMEDOMAIN1 = 'acmedomain1';

    public const ACMEDOMAIN2 = 'acmedomain2';

    public const ACMEDOMAIN3 = 'acmedomain3';

    public const ACMEDOMAIN4 = 'acmedomain4';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACME,
            self::ACMEDOMAIN0,
            self::ACMEDOMAIN1,
            self::ACMEDOMAIN2,
            self::ACMEDOMAIN3,
            self::ACMEDOMAIN4
        ];
    }
}


