<?php
/**
 * PdmNodesNetworkInlineEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pdm\Model;
use \ClientApi\Pdm\ObjectSerializer;

/**
 * PdmNodesNetworkInlineEnum Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PdmNodesNetworkInlineEnum
{
    /**
     * Possible values of this enum
     */
    public const CIDR = 'cidr';

    public const CIDR6 = 'cidr6';

    public const GATEWAY = 'gateway';

    public const GATEWAY6 = 'gateway6';

    public const METHOD = 'method';

    public const METHOD6 = 'method6';

    public const COMMENTS = 'comments';

    public const COMMENTS6 = 'comments6';

    public const MTU = 'mtu';

    public const AUTOSTART = 'autostart';

    public const BRIDGE_PORTS = 'bridge_ports';

    public const BRIDGE_VLAN_AWARE = 'bridge_vlan_aware';

    public const SLAVES = 'slaves';

    public const BOND_PRIMARY = 'bond-primary';

    public const BOND_XMIT_HASH_POLICY = 'bond_xmit_hash_policy';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CIDR,
            self::CIDR6,
            self::GATEWAY,
            self::GATEWAY6,
            self::METHOD,
            self::METHOD6,
            self::COMMENTS,
            self::COMMENTS6,
            self::MTU,
            self::AUTOSTART,
            self::BRIDGE_PORTS,
            self::BRIDGE_VLAN_AWARE,
            self::SLAVES,
            self::BOND_PRIMARY,
            self::BOND_XMIT_HASH_POLICY
        ];
    }
}


