<?php
/**
 * PdmPveRemotesTypeEnum2
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pdm\Model;
use \ClientApi\Pdm\ObjectSerializer;

/**
 * PdmPveRemotesTypeEnum2 Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PdmPveRemotesTypeEnum2
{
    /**
     * Possible values of this enum
     */
    public const BRIDGE = 'bridge';

    public const BOND = 'bond';

    public const ETH = 'eth';

    public const ALIAS = 'alias';

    public const VLAN = 'vlan';

    public const FABRIC = 'fabric';

    public const OVS_BRIDGE = 'OVSBridge';

    public const OVS_BOND = 'OVSBond';

    public const OVS_PORT = 'OVSPort';

    public const OVS_INT_PORT = 'OVSIntPort';

    public const VNET = 'vnet';

    public const UNKNOWN = 'unknown';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BRIDGE,
            self::BOND,
            self::ETH,
            self::ALIAS,
            self::VLAN,
            self::FABRIC,
            self::OVS_BRIDGE,
            self::OVS_BOND,
            self::OVS_PORT,
            self::OVS_INT_PORT,
            self::VNET,
            self::UNKNOWN
        ];
    }
}


