<?php
/**
 * PdmStatusEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pdm\Model;
use \ClientApi\Pdm\ObjectSerializer;

/**
 * PdmStatusEnum Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PdmStatusEnum
{
    /**
     * Possible values of this enum
     */
    public const _NEW = 'new';

    public const NOTFOUND = 'notfound';

    public const ACTIVE = 'active';

    public const INVALID = 'invalid';

    public const EXPIRED = 'expired';

    public const SUSPENDED = 'suspended';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_NEW,
            self::NOTFOUND,
            self::ACTIVE,
            self::INVALID,
            self::EXPIRED,
            self::SUSPENDED
        ];
    }
}


