<?php
/**
 * PveRemotesCreatePveRemotesByRemoteQemuByVmidRemoteMigrateRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pdm\Model;

use \ArrayAccess;
use \ClientApi\Pdm\ObjectSerializer;

/**
 * PveRemotesCreatePveRemotesByRemoteQemuByVmidRemoteMigrateRequest Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pdm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PveRemotesCreatePveRemotesByRemoteQemuByVmidRemoteMigrateRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PveRemotesCreatePveRemotesByRemoteQemuByVmidRemote_migrateRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'bwlimit' => 'int',
        'delete' => 'bool',
        'node' => 'string',
        'online' => 'bool',
        'target' => 'string',
        'target_bridge' => 'string[]',
        'target_endpoint' => 'string',
        'target_storage' => 'string[]',
        'target_vmid' => 'int',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'bwlimit' => 'int64',
        'delete' => null,
        'node' => null,
        'online' => null,
        'target' => null,
        'target_bridge' => null,
        'target_endpoint' => null,
        'target_storage' => null,
        'target_vmid' => 'int64',
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'bwlimit' => false,
        'delete' => false,
        'node' => false,
        'online' => false,
        'target' => false,
        'target_bridge' => false,
        'target_endpoint' => false,
        'target_storage' => false,
        'target_vmid' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bwlimit' => 'bwlimit',
        'delete' => 'delete',
        'node' => 'node',
        'online' => 'online',
        'target' => 'target',
        'target_bridge' => 'target-bridge',
        'target_endpoint' => 'target-endpoint',
        'target_storage' => 'target-storage',
        'target_vmid' => 'target-vmid',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bwlimit' => 'setBwlimit',
        'delete' => 'setDelete',
        'node' => 'setNode',
        'online' => 'setOnline',
        'target' => 'setTarget',
        'target_bridge' => 'setTargetBridge',
        'target_endpoint' => 'setTargetEndpoint',
        'target_storage' => 'setTargetStorage',
        'target_vmid' => 'setTargetVmid',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bwlimit' => 'getBwlimit',
        'delete' => 'getDelete',
        'node' => 'getNode',
        'online' => 'getOnline',
        'target' => 'getTarget',
        'target_bridge' => 'getTargetBridge',
        'target_endpoint' => 'getTargetEndpoint',
        'target_storage' => 'getTargetStorage',
        'target_vmid' => 'getTargetVmid',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('bwlimit', $data ?? [], null);
        
        $this->setIfExists('delete', $data ?? [], false);
        
        $this->setIfExists('node', $data ?? [], null);
        
        $this->setIfExists('online', $data ?? [], false);
        
        $this->setIfExists('target', $data ?? [], null);
        
        $this->setIfExists('target_bridge', $data ?? [], null);
        
        $this->setIfExists('target_endpoint', $data ?? [], null);
        
        $this->setIfExists('target_storage', $data ?? [], null);
        
        $this->setIfExists('target_vmid', $data ?? [], null);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        if (!is_null($this->container['bwlimit']) && ($this->container['bwlimit'] < 0)) {
            $invalidProperties[] = "invalid value for 'bwlimit', must be bigger than or equal to 0.";
        }

        
        
        if (!is_null($this->container['node']) && !preg_match("/^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/", $this->container['node'])) {
            $invalidProperties[] = "invalid value for 'node', must be conform to the pattern /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/.";
        }

        
        
        if ($this->container['target'] === null) {
            $invalidProperties[] = "'target' can't be null";
        }
        if ((mb_strlen($this->container['target']) > 32)) {
            $invalidProperties[] = "invalid value for 'target', the character length must be smaller than or equal to 32.";
        }

        if ((mb_strlen($this->container['target']) < 2)) {
            $invalidProperties[] = "invalid value for 'target', the character length must be bigger than or equal to 2.";
        }

        if (!preg_match("/^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/", $this->container['target'])) {
            $invalidProperties[] = "invalid value for 'target', must be conform to the pattern /^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/.";
        }

        
        if ($this->container['target_bridge'] === null) {
            $invalidProperties[] = "'target_bridge' can't be null";
        }
        
        
        if ($this->container['target_storage'] === null) {
            $invalidProperties[] = "'target_storage' can't be null";
        }
        
        if (!is_null($this->container['target_vmid']) && ($this->container['target_vmid'] < 1)) {
            $invalidProperties[] = "invalid value for 'target_vmid', must be bigger than or equal to 1.";
        }

        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets bwlimit
     *
     * @return int|null
     */
    public function getBwlimit()
    {
        return $this->container['bwlimit'];
    }

    /**
     * Sets bwlimit
     *
     * @param int|null $bwlimit Override I/O bandwidth limit (in KiB/s).
     *
     * @return self
     */
    public function setBwlimit($bwlimit)
    {
        if (is_null($bwlimit)) {
            throw new \InvalidArgumentException('non-nullable bwlimit cannot be null');
        }

        if (($bwlimit < 0)) {
            throw new \InvalidArgumentException('invalid value for $bwlimit when calling PveRemotesCreatePveRemotesByRemoteQemuByVmidRemoteMigrateRequest., must be bigger than or equal to 0.');
        }

        $this->container['bwlimit'] = $bwlimit;

        return $this;
    }
    

    /**
     * Gets delete
     *
     * @return bool|null
     */
    public function getDelete()
    {
        return $this->container['delete'];
    }

    /**
     * Sets delete
     *
     * @param bool|null $delete Delete the original VM and related data after successful migration.
     *
     * @return self
     */
    public function setDelete($delete)
    {
        if (is_null($delete)) {
            throw new \InvalidArgumentException('non-nullable delete cannot be null');
        }
        $this->container['delete'] = $delete;

        return $this;
    }
    

    /**
     * Gets node
     *
     * @return string|null
     */
    public function getNode()
    {
        return $this->container['node'];
    }

    /**
     * Sets node
     *
     * @param string|null $node Node name (or 'localhost')
     *
     * @return self
     */
    public function setNode($node)
    {
        if (is_null($node)) {
            throw new \InvalidArgumentException('non-nullable node cannot be null');
        }

        if ((!preg_match("/^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/", ObjectSerializer::toString($node)))) {
            throw new \InvalidArgumentException("invalid value for \$node when calling PveRemotesCreatePveRemotesByRemoteQemuByVmidRemoteMigrateRequest., must conform to the pattern /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?)$/.");
        }

        $this->container['node'] = $node;

        return $this;
    }
    

    /**
     * Gets online
     *
     * @return bool|null
     */
    public function getOnline()
    {
        return $this->container['online'];
    }

    /**
     * Sets online
     *
     * @param bool|null $online Perform an online migration if the vm is running.
     *
     * @return self
     */
    public function setOnline($online)
    {
        if (is_null($online)) {
            throw new \InvalidArgumentException('non-nullable online cannot be null');
        }
        $this->container['online'] = $online;

        return $this;
    }
    

    /**
     * Gets target
     *
     * @return string
     */
    public function getTarget()
    {
        return $this->container['target'];
    }

    /**
     * Sets target
     *
     * @param string $target Remote ID.
     *
     * @return self
     */
    public function setTarget($target)
    {
        if (is_null($target)) {
            throw new \InvalidArgumentException('non-nullable target cannot be null');
        }
        if ((mb_strlen($target) > 32)) {
            throw new \InvalidArgumentException('invalid length for $target when calling PveRemotesCreatePveRemotesByRemoteQemuByVmidRemoteMigrateRequest., must be smaller than or equal to 32.');
        }
        if ((mb_strlen($target) < 2)) {
            throw new \InvalidArgumentException('invalid length for $target when calling PveRemotesCreatePveRemotesByRemoteQemuByVmidRemoteMigrateRequest., must be bigger than or equal to 2.');
        }
        if ((!preg_match("/^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/", ObjectSerializer::toString($target)))) {
            throw new \InvalidArgumentException("invalid value for \$target when calling PveRemotesCreatePveRemotesByRemoteQemuByVmidRemoteMigrateRequest., must conform to the pattern /^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/.");
        }

        $this->container['target'] = $target;

        return $this;
    }
    

    /**
     * Gets target_bridge
     *
     * @return string[]
     */
    public function getTargetBridge()
    {
        return $this->container['target_bridge'];
    }

    /**
     * Sets target_bridge
     *
     * @param string[] $target_bridge List of bridge mappings
     *
     * @return self
     */
    public function setTargetBridge($target_bridge)
    {
        if (is_null($target_bridge)) {
            throw new \InvalidArgumentException('non-nullable target_bridge cannot be null');
        }
        $this->container['target_bridge'] = $target_bridge;

        return $this;
    }
    

    /**
     * Gets target_endpoint
     *
     * @return string|null
     */
    public function getTargetEndpoint()
    {
        return $this->container['target_endpoint'];
    }

    /**
     * Sets target_endpoint
     *
     * @param string|null $target_endpoint The target endpoint to use for the connection.
     *
     * @return self
     */
    public function setTargetEndpoint($target_endpoint)
    {
        if (is_null($target_endpoint)) {
            throw new \InvalidArgumentException('non-nullable target_endpoint cannot be null');
        }
        $this->container['target_endpoint'] = $target_endpoint;

        return $this;
    }
    

    /**
     * Gets target_storage
     *
     * @return string[]
     */
    public function getTargetStorage()
    {
        return $this->container['target_storage'];
    }

    /**
     * Sets target_storage
     *
     * @param string[] $target_storage List of storage mappings
     *
     * @return self
     */
    public function setTargetStorage($target_storage)
    {
        if (is_null($target_storage)) {
            throw new \InvalidArgumentException('non-nullable target_storage cannot be null');
        }
        $this->container['target_storage'] = $target_storage;

        return $this;
    }
    

    /**
     * Gets target_vmid
     *
     * @return int|null
     */
    public function getTargetVmid()
    {
        return $this->container['target_vmid'];
    }

    /**
     * Sets target_vmid
     *
     * @param int|null $target_vmid A guest ID
     *
     * @return self
     */
    public function setTargetVmid($target_vmid)
    {
        if (is_null($target_vmid)) {
            throw new \InvalidArgumentException('non-nullable target_vmid cannot be null');
        }

        if (($target_vmid < 1)) {
            throw new \InvalidArgumentException('invalid value for $target_vmid when calling PveRemotesCreatePveRemotesByRemoteQemuByVmidRemoteMigrateRequest., must be bigger than or equal to 1.');
        }

        $this->container['target_vmid'] = $target_vmid;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



